### ISSUE TITLE
define function is incorrect

### ISSUE THREAD

**Issue by wolfadex** [i18next/i18next-browser-languageDetector#128]
Line 3 of i18nextBrowserLanguageDetector.js in the bower package is incorrect. It currently reads `typeof define === 'function' && define.amd ? define('i18nextBrowserLanguageDetector', factory) :` when it should be `typeof define === 'function' && define.amd ? define(factory) :`. This causes LngDetector to be `undefined` when required.

**Comment by jamuhl** [comment]
just published i18next-browser-languagedetector@1.0.0 removing the named amd export
