### ISSUE TITLE
s.languageDetector.init is not a function

### ISSUE THREAD

**Issue by don-bluelinegrid** [i18next/i18next-browser-languageDetector#129]
Using i18next 3.4.1/i18next-browser-languageDetector 1.0.0 with typescript/webpack

Building using typescript/webpack, a webpack build completes without errors.  Loading the (Aurelia) application in a browser gives the following error:

```
bluebird.js:5119TypeError: s.languageDetector.init is not a function
    at I18n.init (http://localhost:9000/app.bundle.js:3410:28)
    at http://localhost:9000/app.bundle.js:37447:63
    at registerI18N (http://localhost:9000/app.bundle.js:24583:13)
    at Object.configure (http://localhost:9000/app.bundle.js:24645:26)
    at http://localhost:9000/aurelia.bundle.js:12891:34
From previous event:
    at _loadPlugin (http://localhost:9000/aurelia.bundle.js:12889:40)
    at http://localhost:9000/aurelia.bundle.js:12882:14
From previous event:
    at loadPlugin (http://localhost:9000/aurelia.bundle.js:12881:73)
    at next (http://localhost:9000/aurelia.bundle.js:13142:18)
From previous event:
    at next (http://localhost:9000/aurelia.bundle.js:13142:54)
    at http://localhost:9000/aurelia.bundle.js:13149:14
From previous event:
    at FrameworkConfiguration.apply (http://localhost:9000/aurelia.bundle.js:13134:42)
    at Aurelia.start (http://localhost:9000/aurelia.bundle.js:12751:21)
    at Object._callee$ (http://localhost:9000/app.bundle.js:37479:40)
    at tryCatch (http://localhost:9000/aurelia-bootstrap.bundle.js:3189:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (http://localhost:9000/aurelia-bootstrap.bundle.js:3463:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (http://localhost:9000/aurelia-bootstrap.bundle.js:3222:21)
    at http://localhost:9000/app.bundle.js:37390:65
From previous event:
    at __awaiter (http://localhost:9000/app.bundle.js:37370:12)
    at Object.configure (http://localhost:9000/app.bundle.js:37413:12)
    at http://localhost:9000/aurelia-bootstrap.bundle.js:15254:27
From previous event:
    at config (http://localhost:9000/aurelia-bootstrap.bundle.js:15253:46)
    at handleApp (http://localhost:9000/aurelia-bootstrap.bundle.js:15244:10)
    at http://localhost:9000/aurelia-bootstrap.bundle.js:15272:9
From previous event:
    at http://localhost:9000/aurelia-bootstrap.bundle.js:15269:44
From previous event:
    at run (http://localhost:9000/aurelia-bootstrap.bundle.js:15266:24)
    at Object.<anonymous> (http://localhost:9000/aurelia-bootstrap.bundle.js:15291:1)
    at Object.aurelia-bootstrapper-webpack (http://localhost:9000/aurelia-bootstrap.bundle.js:15292:30)
    at __webpack_require__ (http://localhost:9000/aurelia-bootstrap.bundle.js:57:38)
    at Object.184 (http://localhost:9000/aurelia-bootstrap.bundle.js:7252:1)
    at __webpack_require__ (http://localhost:9000/aurelia-bootstrap.bundle.js:57:38)
    at 0 (http://localhost:9000/aurelia-bootstrap.bundle.js:140:18)
    at http://localhost:9000/aurelia-bootstrap.bundle.js:143:10
```

**Comment by don-bluelinegrid** [comment]
Note -

Background:

When importing languagedetector in TypeScript like this:

```
import LngDetector from 'i18next-browser-languagedetector';
```

we get the following error:

```
[default] Checking started in a separate process...
[default] /Users/donpeterkofsky/Documents/gc-2/src/main.ts:11:8 
    Module '"/Users/donpeterkofsky/Documents/gc-2/node_modules/i18next-browser-languagedetector/index"' has no default export.
[default] Checking finished with 1 errors
```

If we change the import to this:

```
import * as LngDetector from 'i18next-browser-languagedetector';
```

we get the error noted above, in the web browser console.

So, it seems there may be an issue with the typings, or the exported type?

**Comment by jamuhl** [comment]
```
[default] Checking started in a separate process...
[default] /Users/donpeterkofsky/Documents/gc-2/src/main.ts:11:8 
    Module '"/Users/donpeterkofsky/Documents/gc-2/node_modules/i18next-browser-languagedetector/index"' has no default export.
[default] Checking finished with 1 errors
```

looks like you try to transform the `/Users/donpeterkofsky/Documents/gc-2/node_modules/i18next-browser-languagedetector/index` on import -> there is no default export as this is a regular commonjs export

for importing jsnext (es6 import/export) try using import LngDetector from 'i18next-browser-languagedetector/dist/es/index.js';

but personally i never had to do this on webpack....are you using beta of webpack 2? or else it must be related to typescript...

**Comment by don-bluelinegrid** [comment]
I am using typescript + webpack, in an Aurelia project.

Yes, the change above does work, to eliminate the issue.  However, that does not appear to be the expected practice for use with TypeScript.  There are many users out there using typescript with Aurelia or Angular2.  And, for Aurelia, they are including i18next as a dependency in their aurelia-i18n module.  So, this really should be fixed, to provide a proper default typed export.

**Comment by jamuhl** [comment]
not sure...i believe something is wrong in the config you use. eg. using babel to transform es6 you don't transform modules loaded in node_modules as they are expected to be not delievered in es6 (as that is not supported in all browsers).

for the case a build chain support es6 transform incl. treeshaking the build tool should resolve jsnext:main entrance point defined in package.json.

how do you import i18next? it has the same export like the browser language detector...

**Comment by don-bluelinegrid** [comment]
There seems to be a misunderstanding.

I am using webpack, which compiles typescript (.ts) files.  Webpack would not do any transformation on the node_monules JavaScript (.js) files.

I do not import i18next, as I said above, i18next is a dependency of the aurelia-i18n module, and they import it into their source files, in the typescript typing file, like this:
```
import i18next from 'i18next';
```

I do import the i18next-xhr-backend module, like this:
```
import Backend from 'i18next-xhr-backend';
```

There are a couple of differences that I see in the commonjs files for i18next compared to i18next-browser-detector:

1. In i18next, the return type is declared like this: ```exports.default = new I18n();``` In browser detector, the return type is like this:  ```exports.default = Browser;```  So, in the first case it looks like the export is an instance of an object, in the second case it looks like a function.

2. In i18next, there is a distributable file in the commonjs directory named ```i18next.js```, which referes to another file ```i18next.js```, and which does some trickery to gaurantee that a default export is present; in the browser-detector, there is only a distributable file named ```index.js```.

So, I do see differences, and #2 seems like it may be related to the issue.

**Comment by jamuhl** [comment]
#2 is only a check on passed in options - asserting an array is passed in.

for the differences:

1) is true: i18next exposes an instance while the other exposes a constructor

2)

i18next:

```
// package.json -> regular export of a commonjs file
"main": "./index.js",

// /index.js -> commonjs export for the dist files export.default
module.exports = require('./dist/commonjs/index.js').default;

// /dist/commonjs/index.js -> exports an export
exports.default = _i18next2.default;
```

i18next-browserLangauge-detector:

```
// package.json -> regular export of a commonjs file
"main": "./index.js",

// /index.js -> commonjs export for the dist files export.default
module.exports = require('./dist/commonjs/index.js').default;

// /dist/commonjs/index.js -> exports directly (but basically the same)
exports.default = Browser;
```

So for me it seems more an issue of the typescript loader like eg. https://github.com/Microsoft/TypeScript/issues/9725#issuecomment-232765825 but as i'm not use typescript it's hard for me to find the root cause of this issue. But like said...on a non-typescript build chain we never heard of such an issue. Might be the `.ts` file you use has some wrong statement in it?

**Comment by jamuhl** [comment]
`import LngDetector from 'i18next-browser-languagedetector';`
we get the following error:

```
[default] Checking started in a separate process...
[default] /Users/donpeterkofsky/Documents/gc-2/src/main.ts:11:8 
    Module '"/Users/donpeterkofsky/Documents/gc-2/node_modules/i18next-browser-languagedetector/index"' has no default export.
[default] Checking finished with 1 errors
````

The import statement is correct -> the check is wrong - there is no default export on `/i18next-browser-languagedetector/index` which is the correct thing to do. So it really seems the .ts file has a wrong statement for that.

**Comment by don-bluelinegrid** [comment]
@jamuhl 

Jan,

I'm confused by the comment above.  I'll try to summarize the facts:

1. You've said that there is likely to be some problem with the TypeScript config, which would be specific to the LangDetector module.  There is *no module-specific config*.  The config would affect all modules in the same way.

2. You've said that it is the correct thing to do, to *not expose a default export for a module*.   Does this make sense, if you want the module to be easily compatible with/usable by TypeScript? See https://www.typescriptlang.org/docs/handbook/modules.html

3. You are suggesting that there is a problem with the TypeScript loader based on a comment in the TypeScript git project.  But if you fully read through the comment, you'll see that the original problem was determined to be with a module for AngularJS, and the module author fixed the problem.

4. Most fully TypeScript-compatible modules are providing typings files (i.e., langDetector.d.ts) to facilitate use with TypeScript. The  i18next modules do not consistently provide these:
- For base i18next, there are no typings provided; in fact, the aurelia-i18n project itself has had to provide typings for i18next themselves.
- For i18next-xhr-backend, there is a /typings directory with a proper typings file.
- For i18next-browser-languagedetector, there are no typings available.
I suspect the lack of the typings file is the cause of the issue that I'm reporting.

I realize that you may not be an expert with TypeScript - I am not an expert either, as I've learned it as part of starting a project with the Aurelia framework.  However, two of the major JS frameworks (Aurelia and Angular2) and Microsoft are fully committed to TS, which means many developers are using it.  And, your i18next module is being used as a dependency in the aurelia-i18n module, which means many Aurelia users will be exposed to your module.  I am doing a commercial project now with Aurelia, which will be internationalized, and so I am incorporating the framework early in the development process.

It would seem to be advantageous to take care of making the module fully compatible with TS now, before many more users run into issues and begin logging them here as issues on your GitHub.  Perhaps collaborating with the Aurelia team from their aurelia-i18n module could be helpful?

**Comment by jamuhl** [comment]
reading the provided link: https://www.typescriptlang.org/docs/handbook/modules.html 

look at the section `export = and import = require()`:

`import zip = require("./ZipCodeValidator");`

seems to be the way to use commonjs modules => which most modules provided via npm are.

- typescript is recommended on angular2 but no need (fully optional)
- not every module is backed by a large company...i work solo on i18next in my free time. trading time with my family to give people what it is.
- just because another module (aurelia) uses i18next and prefer typescript does not enforce i18next to adapt to it - i18next is used in a lot of frameworks for i18n
- .ts files can be found here: https://github.com/DefinitelyTyped/DefinitelyTyped -> can be updated by community preferring to use typescript

**Comment by jamuhl** [comment]
remove the typings from i18next-xhr-backend in favour to https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by jamuhl** [comment]
further see http://stackoverflow.com/questions/29596714/new-es6-syntax-for-importing-commonjs-amd-modules-i-e-import-foo-require
