### ISSUE TITLE
setup similar language use one language

### ISSUE THREAD

**Issue by tailnode** [i18next/i18next-browser-languageDetector#130]
Hi
i have two folders(zh and en) to store language data, and i18next-browser-languageDetector detect language may be 'zh', 'zh-CN', 'zh-TW', 'en', 'en-US' etc
i want the chinese('zh','zh-CN' etc) use data in folder 'zh' and english('en', 'en-US' etc) use data in folder 'en'.
but i don't know how to set i18next to satisfy my demand, could you tell me how to do this.
thanks.

**Comment by jamuhl** [comment]
try init with options `{ load: 'languageOnly' }`

**Comment by tailnode** [comment]
option `{ load: 'languageOnly' }` is ok, thank you. : )
