### ISSUE TITLE
cannot import into rollup bundle

### ISSUE THREAD

**Issue by robhicks** [i18next/i18next-browser-languageDetector#131]
In rollup, this fails:

``` JavaScript
import lngDetector from 'i18next-browser-languagedetector';

```

Here's the error:

``` sh
Module /Users/.../node_modules/i18next-browser-languagedetector/dist/es/index.js does not export default (imported by /Users/.../public/src/index.js)
```

**Comment by jamuhl** [comment]
can you check...my version of `/dist/es/index.js` has `exports.default = Browser;` on last line...not sure why it states it not like that...

**Comment by robhicks** [comment]
The last line of dist/es/index.js does indeed include exports.default = Browser;

**Comment by jamuhl** [comment]
no idea...anyone an idea?
