### ISSUE TITLE
Safari 10: SecurityError (DOM Exception 18): The operation is insecure.

### ISSUE THREAD

**Issue by medialwerk** [i18next/i18next-browser-languageDetector#132]
If Safari 10 does not allow access to the local storage this error is thrown: "SecurityError (DOM Exception 18): The operation is insecure".

This happens because of these lines: 

https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/browserLookups/localStorage.js#L29

https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/browserLookups/localStorage.js#L38

Safari already throws this error if you access "window.localStorage".

Thanks! :-)

**Comment by jamuhl** [comment]
hm seems same as: https://github.com/angular-translate/angular-translate/issues/629

means only solution is putting all in a try-catch block and have a silent failure...means no cookie and no localStorage -> changeLanguage won't be persisted on session refresh - which might be ok in this cases...who turns off cookies anyway.

If you like you might provide a PR to speed it up...else i will try to make the change when i'm back from holiday.

**Comment by medialwerk** [comment]
Hey jamuhl,

i am a little bit busy these days too. If i find some spare time to provide a pull request, i let you know. Thanks for your proposal to fix it after your holiday! :-).

**Comment by jamuhl** [comment]
@medialwerk can you try i18next-browser-languagedetector@1.0.1 that should avoid triggering this exception using the try-catch block
