### ISSUE TITLE
Navigator browser lookup does not return only the language

### ISSUE THREAD

**Issue by medialwerk** [i18next/i18next-browser-languageDetector#133]
Hello! :-),

The navigator browser lookup does not consider the i18next configuration option `load: languageOnly`. If the navigator has following languages `['en-US', 'en']` the i18next language (`i18next.language`) will be `en-US` and not only `en`.

Is this an i18next issue or an issue of this library?

Thanks!

**Comment by jamuhl** [comment]
i18next.language will always be the detected language independent of what i18next will use to find translations -> use i18next.languages to see what locals will be used in order to lookup translations.

**Comment by medialwerk** [comment]
i18next.languages is ["de", "en"], i18next.language is "de-de". I want to get the language only string, to know which main language is set. Is there any api function for that or do i have to strip it by myself with `18next.services.languageUtils.getLanguagePartFromCode`? :-)

Thanks!

**Comment by jamuhl** [comment]
`i18next.languages[0]` or `18next.services.languageUtils.getLanguagePartFromCode` ;)

**Comment by medialwerk** [comment]
`i18next.languages[0]` is perfect, thank you!
