### ISSUE TITLE
How can I see which language was detected?

### ISSUE THREAD

**Issue by cjs1976** [i18next/i18next-browser-languageDetector#134]
Hi,

I have some troubles with the implementation. Is there a way to show the detected language?

Thanks,
Christian.

**Comment by jamuhl** [comment]
detected language will be on `i18next.language` while an ordered array of languages which will be used to lookup a key will be on `i18next.languages.`

**Comment by cjs1976** [comment]
Hi jamuhl,

thank you for the quick reply. I tried this, but it didn't work. I had the wrong name for this plugin. If someone runs into the same problem, this is the right way:

`
i18next
	.use(i18nextBrowserLanguageDetector)
	.use(i18nextXHRBackend)
	.init({ ...
`
