### ISSUE TITLE
I still have some issues to understand the plugin.

### ISSUE THREAD

**Issue by cjs1976** [i18next/i18next-browser-languageDetector#135]
Hi,

my idea is:

1. If the user opens my website, than there is no information, so I have to detect the browser language, and translate the website in the detected language.

2. Now I know the language, so on the next page I don't need to detect the language from the browser, I need to use the language which was used one page before.

How can I solve this out?

Thanks,
Christian.

**Comment by jamuhl** [comment]
the detector is also responsible to cache the detected language over requests / sessions:

https://github.com/i18next/i18next-browser-languageDetector#detector-options --> `cache` you can set an array of where to cache, so eg. if you use cache on localStorage on next request it will lookup the language in that (also if a user changes language and you toggle that using i18next.changeLanguage it will be persisted)

**Comment by jamuhl** [comment]
some advertising in own topic - we got a translation management service http://locize.com which could enhance your experience using i18next

**Comment by cjs1976** [comment]
Hi Jamuhl,

again thank you for the quick reply. But:

1. Do I need the caching plugin or does this already work?

2. What happens if the user changes the language. E.g. german was detected, but the user changed to italian because he wants to use italian.

Thanks,
Christian.

**Comment by jamuhl** [comment]
for caching detected language you do not need the caching plugin...that's built into the detector.

changing language will be persisted

the cache plugin is for caching the loaded translations on client.
