### ISSUE TITLE
Not working to get language preferences from FireFox

### ISSUE THREAD

**Issue by MarcoMedrano** [i18next/i18next-browser-languageDetector#136]
I set my firefox language preferences to have spanish first :
![image](https://cloud.githubusercontent.com/assets/2736856/24016167/7f84d680-0a61-11e7-9bb8-7dafce591b07.png)
But the plugin seems not detecting it. *QueryStrings* are working fine.

**Comment by jamuhl** [comment]
could you please paste your init options...thank you

**Comment by MarcoMedrano** [comment]
Yeah, almost no init options:
`i18next.use(LngDetector).init({
   keySeparator: false,
   resources: ....
   });`

That is all.

**Comment by MarcoMedrano** [comment]
Probably is something wrong with firefox :S , after use the query string with **es** , yes it worked, but when I remove it, it does not want to come back to **en**, even I configured language preferences again to put **en** on the top, but I am still having spanish now. I restarted multiple times >.<

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next-browser-languageDetector#detector-options there is the caches  array. Means after a detection (or manual change via i18next.changeLanguage) the new lng value is stored on localStorage or cookie (whatever is set). On every subsequent load it will use that value (if higher in the detection order. Hope that is understandable...

So if nothing else detected it will take lng from navigator - once persisted it will take the persisted value (clear that from localStorage or cookie for new detection from navigator)

**Comment by MarcoMedrano** [comment]
Ho man, yeah I think that was it. In my beginning tests I used `lng: 'en'` So I guess it was cached, then when I wanted to use your plugging, it got that from cache (cookies or localStorage) and no matter what I tried in the navigator.

I used the options you suggested to put the browser as first option, and all started to work as expected.
Thanks man! appreciated.

Postdata, probably would be better to change the default order, cookies and localstorage imho are used explicitly and require extra work and is a bit hard to realize third libs are using it,  also for demo proposals browser priority would be nice.

**Comment by jamuhl** [comment]
ah...if you init with `lng` set in options it not even will do detection...will always use that value.

**Comment by MarcoMedrano** [comment]
yep I just init once or twice with that, then removed it, but I guess that was enough to make i18next to cache it.

**Comment by MarcoMedrano** [comment]
Thank you!  I think will be my next step (:.
