### ISSUE TITLE
TypeError: Cannot read property 'languageUtils' of undefined

### ISSUE THREAD

**Issue by horseyman** [i18next/i18next-browser-languageDetector#137]
I have been struggling for a while to get the languageDetector working.

I am making a web application using Aurelia.. 
At startup, I was invoking the Language Detection exactly as described here in the 
documentation, but the application always returned a:

TypeError: Cannot read property 'languageUtils' of undefined, 

caused by i18nextBrowserLanguageDetector.js, line 258: 
 "var cleanedLng = _this.services.languageUtils.formatLanguageCode(lng);"

An analysis showed me that this invocation happens within the Browser function that gets 
constructed using a services reference, and I didn't manage to find out how on earth 
that reference gets passed to the Browser function, when implementing according to the 
documentation..

Constructing the LngDetector with a reference to i18next.services solves the problem, 
I may be mistaken in something, and I'd love to understand what that could be, 
or perhaps its just the documentation that needs to be updated?

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next-browser-languageDetector#getting-started

```
import i18next from 'i18next';
import LngDetector from 'i18next-browser-languagedetector';

i18next
  .use(LngDetector) // <------
```

that will init it correctly

**Comment by horseyman** [comment]
Sorry, when I 'init' it like this, and then perform a detect(), the exception arises.
Exactly like I wrote in the issue.

**Comment by jamuhl** [comment]
not sure but: https://github.com/i18next/i18next/blob/master/src/i18next.js#L89

rather sure you do something different...can you paste your init code?

**Comment by horseyman** [comment]
Thank you for that reference.. 
sure I could send you the initialization code, and I wouldn't mind to share it, but for now I'd like to clean that up and spare you the headache.. 
Based on what I saw in the reference, I now get a reference to the languageDetector using 
`i18next.services.languageDetector`, and that works perfectly!
Is that the recommended way? So far, I've simply been invoking the constructor, like `new LngDetector()`
in the implementation, like I saw in other examples, leading to the TypeError.

**Comment by jamuhl** [comment]
if it works it's ok...but normally you should just pass the module to i18next use without constructor call - as i18next will create an instance of that. If you pass an instance your way is ok...

**Comment by horseyman** [comment]
Thats what I'm saying, right now I am passing the module to i18next and do not call any constructor.
Calling the constructor without arguments leads to the TypeError..

**Comment by jamuhl** [comment]
even if calling the constructor without service you only should get that error if calling detect yourself. i18next.init call should set the services anyway later on init of i18next.

But honestly i have no overview how and when aurelia calls init - that's why i ask for some code to check.

If running passing module or instance to use - on init this code runs: https://github.com/i18next/i18next/blob/master/src/i18next.js#L89

setting services and not leading to that error.

**Comment by horseyman** [comment]
I am calling detect myself.. which I now see shouldn't be necessary, since the init() calls the detect.. 
Ok, I think I have been mixing code from different examples without correctly checking the 
implementation itself. Sorry to say, the issue shouldn't be necessary.. 
Ok, I don't mind sharing implementation, also for your insight in Aurelia. The Initialization code was based on https://mttmccb.net/using-i18n-language-detection-with-aurelia/, but I don't mind to send my personal version of that, anything more you'd like?

**Comment by jamuhl** [comment]
correct if adding a detector via use. and not setting a lng on i18next.init -> i18next will call detect itself.

sorry for the confusion getting from different examples...not need for your initialization code...that sample is ok to have a look.

**Comment by DmitryEfimenko** [comment]
I don't think this issue should have been closed. The following code is failing:
```
const lngDetector = new LngDetector();
lngDetector.detect();
```
I had to do the following, but I don't think it should work like that:
```
import LngDetector from 'i18next-browser-languagedetector';
import LanguageUtils from 'i18next/dist/es/LanguageUtils';

const languageUtils = new LanguageUtils({});
const lngDetector = new LngDetector();
lngDetector.init({ languageUtils });
const lng = lngDetector.detect();
```

**Comment by jamuhl** [comment]
@DmitryEfimenko the detector is meant to be used inside of i18next (not standalone)

**Comment by jamuhl** [comment]
@DmitryEfimenko https://www.i18next.com/overview/plugins-and-utils#language-detector
