### ISSUE TITLE
i18next-browser-languageDetector not working on IE 11

### ISSUE THREAD

**Issue by vanthai26** [i18next/i18next-browser-languageDetector#138]
This is my code in i18n.js. It is working fine for all other browsers except for IE. In IE it is always returned as English. Am I doing any thing wrong here?

Thanks

import i18n from 'i18next';
import XHR from 'i18next-xhr-backend';
import LanguageDetector from 'i18next-browser-languagedetector';

var options = {
  // order and from where user language should be detected
  order: ['navigator', 'querystring', 'cookie', 'localStorage', 'htmlTag'],

  // keys or params to lookup language from
  lookupQuerystring: 'lng',
  lookupCookie: 'i18next',
  lookupLocalStorage: 'i18nextLng',

  // cache user language on
  caches: ['localStorage', 'cookie'],

  // optional expire and domain for set cookie
  cookieMinutes: 10,
  cookieDomain: '.lab.net',

  // optional htmlTag with lang attribute, the default is:
  htmlTag: document.documentElement
}

i18n
  .use(XHR)
  .use(LanguageDetector)
  .init({
    detection: options,
    whitelist: ['en', 'da', 'de', 'el', 'fi','fil', 'tl', 'fr','hi','id','it','ja',
    'ko','mr','ms','nl','no','pl','pt-BR','ru','sv','ta','th','tr','uk','vi',
    'zh','zh-TW','da-DK','de-DE','el-GR','fi-FI','fr-FR','hi-IN','it-IT', 'ja-JP',
    'ko-KR', 'nl-NL', 'nb-NO','pl-PL', 'ru-RU','sv-SE', 'th-TH', 'uk-UA','vi-VN','es-XL', ],
    fallbackLng: 'en',
    // have a common namespace used around the full app
    ns: ['common'],
    defaultNS: 'common',
    //debug: true,
    interpolation: {
      escapeValue: false // not needed for react!!
    },
    loadPath: '/locales/{{lng}}/{{ns}}.json',
  });

export default i18n;

**Comment by jamuhl** [comment]
No IE to work with currently...but should work...does it log some error in console?

**Comment by vanthai26** [comment]
I think the problem is IE11 will only return  the language of which it was installed,  in this case it will always be in "en-US"  when  this line is called  "if (navigator.userLanguage)" in navigator.js. 
Is there no reliable "client-side only" solution for this?

**Comment by jamuhl** [comment]
If i remember right - language is whatever is set in IE settings languages. Nothing to do with what is was when installing. Users can change that to whatever is correct to them.

**Comment by nikhil4326** [comment]
What is solution for IE11. its not working with me too

**Comment by nikhil4326** [comment]
Translations are not appearing in IE11 browser only. Below is my code.

```
var options ={
  // order and from where user language should be detected
  order: ['navigator', 'cookie', 'localStorage', 'querystring', 'htmlTag'],

  // keys or params to lookup language from
  lookupQuerystring: 'lng',
  lookupCookie: 'i18next',
  lookupLocalStorage: 'i18nextLng',

  // cache user language on
  caches: ['localStorage', 'cookie'],
  excludeCacheFor: ['cimode'], // languages to not persist (cookie, localStorage)

  // optional expire and domain for set cookie
  cookieMinutes: 10,
  cookieDomain: 'myDomain',

  // optional htmlTag with lang attribute, the default is:
  htmlTag: document.documentElement
}

i18n
  .use(LngDetector)
  .init({
	  detection: options,
    // we init with resources
    resources: {
      en: {
        translations: trans_en
        
      },
      es: {
        translations: trans_es
        
      }	
    },
    fallbackLng: 'en',

    // have a common namespace used around the full app
    ns: ['translations'],
    defaultNS: 'translations',

    keySeparator: false, // we use content as keys

    interpolation: {
      escapeValue: false, // not needed for react!!
      formatSeparator: ','
    },

    react: {
      wait: true
    }
  });
```

**Comment by jamuhl** [comment]
Any warning / error in console?

**Comment by nikhil4326** [comment]
No error/Warning, is the above code correct for IE browser?

**Comment by jamuhl** [comment]
does it work in chrome..than it's ok...at least i see no problem on the first sight. Tried to test the https://www.webpackbin.com/bins/-KvMK7GooEOLVwtqEzgq in IE (using browserstack) but hell shitty IE 11 not supporting object assign.

Do you have any running project i could open in IE to see?

**Comment by nikhil4326** [comment]
https://www.webpackbin.com/bins/-Kw-QQr6pmGZmSnzTVZj
Please check above link. I have reproduced a sample

**Comment by nikhil4326** [comment]
Webpackbin not worked in IE11. 
navigator object will not work for IE11. So i think i need to add customized logic(function) to get language by parsing **accept-language** request header.  Do u know any other best way to achieve the same in IE11?

**Comment by jamuhl** [comment]
not sure...i think it works...https://stackoverflow.com/questions/2678230/how-to-getting-browser-current-locale-preference-using-javascript

Just that value might not be what you expect...

We detect: https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/browserLookups/navigator.js

navigator.languages -> navigator.userLanguage -> navigator.language

**Comment by jamuhl** [comment]
If you need something else just add a custom detector: https://github.com/i18next/i18next-browser-languageDetector#adding-own-detection-functionality

**Comment by nikhil4326** [comment]
I checked, navigator object in IE 11 no more helps you to get browser language. So I did something like below:
In server.js:
`  res.cookie('language', req.get('Accept-Language').split(',')[0])`
In i18n.js

```
var options= {
  order: ['cookie', 'navigator', 'localStorage', 'querystring', 'htmlTag'],
  lookupCookie: 'language'
}

i18n
  .use(LanguageDetector)
  .init({
    detection: options,
    // we init with resources
    resources: .....
});
```
above solution works for all browsers.

**Comment by jamuhl** [comment]
that's what we do in https://github.com/i18next/i18next-express-middleware

**Comment by jamuhl** [comment]
@AlexanderReichl why does your page reload when changing the language? What does your code look like to change language?

**Comment by AlexanderReichl** [comment]
Hi @jamuhl 
thank you for the quick reply. I used to href for the language changer, as follows:

`<a href="index.html?lng=de" title="German" id="lng_de" class="hidden-sm-down languageSelector">DE</a>
<a href="index.html?lng=en" title="English" id="lng_en" class="hidden-sm-down languageSelector">EN</a>`

As I said i18next works perfectly in any other browser. 

If I change debug mode to true I get the following output:
-> i18next::backendConnector: loaded namespace translation for language de [object Object]
-> i18next: languageChanged de

The url param lng=en doesn't seem to take effect.

**Comment by jamuhl** [comment]
Can you please check in your IE

https://locize.com?lng=de
https://locize.com?lng=en

On my IE11 (browserstack) that works...and it uses same detector

**Comment by jamuhl** [comment]
hm...than it's really hard to say where it goes wrong on your app. is the querystring param really there on init time of i18next after reload?

**Comment by jamuhl** [comment]
Best might be you debug the detection logic

**Comment by AlexanderReichl** [comment]
Thank you so far.
You mean debuggin i18nextBrowserLanguageDetector.min.js?

**Comment by jamuhl** [comment]
Would temporary not use the .min - but yes

**Comment by AlexanderReichl** [comment]
Ok I'll do so and get back to you, as soon as I discovered anything.

Many thanks!

**Comment by jamuhl** [comment]
this line: https://github.com/i18next/i18next-browser-languageDetector/blob/master/i18nextBrowserLanguageDetector.js#L91

**Comment by AlexanderReichl** [comment]
I have a guess and I wonder if I may change the language on the fly without using a query link and do a localize on my whole structure?
May I change the language with something like i18next.lng = 'en'?

**Comment by jamuhl** [comment]
`i18next.changeLanguage('de')` or setting it on init `lng: 'de'`

**Comment by AlexanderReichl** [comment]
Yep, that was the solution.  Thank you so much. 

The issue was the sort of single page architecture of the site. And in IE11 the redirect seemed to reload all Javascript like it is an initial start of the page.

Thank you so much! Have a nice weekend.

**Comment by AlexanderReichl** [comment]
Damn, I encountered another little but annoying issue.
`$("#lng_en").click(function() {
	i18next.changeLanguage('en');
	$('body').localize();
});`

So instead of changing language with a href I check if the <a> tag was clicked. If so I change the language to en and do the localize to the whole body.

After clicking once it changes the language setting correctly, but it does not load the translations. The translations are loaded if I click $("#lng_en") a second time.

Any suggetions where that comes from?

**Comment by jamuhl** [comment]
changeLanguage is async...change it to:

`$("#lng_en").click(function() { i18next.changeLanguage('en', function(err) { $('body').localize(); } );  });

`

**Comment by AlexanderReichl** [comment]
It works.
Wonderful! 
Thank you again :)
