### ISSUE TITLE
browser user preference not use correcly

### ISSUE THREAD

**Issue by damienleroux** [i18next/i18next-browser-languageDetector#139]
Hello

I want to report an issue that I'm facing. If I'm wrong, don't hesitate to correct me; I may have miss something in my understanding of how languageDetector works.

Here is my i18n configuration:
```
import i18n from 'i18next';
import LanguageDetector from 'i18next-browser-languagedetector';
import Backend from 'i18next-xhr-backend';
i18n
  .use(Backend)
  .use(LanguageDetector)
	.init({
		fallbackLng: 'en',

		// have a common namespace used around the full app
		ns: ['common'],
		defaultNS: 'common',

		debug: true,
		backend: {
			loadPath: '/src/i18n/{{lng}}/{{ns}}.json'
		},

		interpolation: {
			escapeValue: false, // not needed for react!!
			formatSeparator: ',',
			format: (value, format, lng) => {
				if (format === 'uppercase') return value.toUpperCase();
				return value;
			}
		}
	});
```

Here is my chrome configuration:
![image](https://cloud.githubusercontent.com/assets/12717418/24894794/e655cec0-1e8c-11e7-933c-ae17352a9327.png)

As you can see, I'm french (my default chrome configuration) but prefer to work in English. I have added the English language and set it as "to use as default":

![image](https://cloud.githubusercontent.com/assets/12717418/24895218/87dcfd7a-1e8f-11e7-9c7e-7506b864a6e9.png)

When loading my site the first time (no local storage of any kind), `navigator.js` will [load the navigator languages settings](https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/browserLookups/navigator.js#L10):

![image](https://cloud.githubusercontent.com/assets/12717418/24894868/5c4b1086-1e8d-11e7-8006-da6fcc99f3fa.png)

Then will [load the chosen preferred language](https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/browserLookups/navigator.js#L17). Chrome set, in the variable `navigator.language`, the language I have chosen as default:

![image](https://cloud.githubusercontent.com/assets/12717418/24894888/86e4e286-1e8d-11e7-83b0-69acd43f4646.png)

As a result, here is the `lookup` (from `index.js`):

![image](https://cloud.githubusercontent.com/assets/12717418/24894914/a2638a80-1e8d-11e7-8bd0-9b9bbdc67721.png)

My problem is in the next [loop to find the "found" language](https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/index.js#L59): The first element in the array is used as found. Therefore, the user preferred language, that was put at the end of all other navigator defined languages, is never used.

I believe that the user preferred language should have a higher priority than other defined language:
Could we change line: 
[found.push(navigator.language);](https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/browserLookups/navigator.js#L17)
into:
`found.unshift(navigator.language);`
This way, it will be used first.

Let me know if I miss the point of if there is a solution for my problem.

I can pull a request if you want.

Thank you

**Comment by jamuhl** [comment]
the point is navigator.languages is the preferred languages ordered by priority -> currently we pick the first and let i18next handle further prios - but basically we could extend that to enable user defined fallbacks to second preferred language,...

navigator.language here acts only as a fallback if navigator.languages (experimental) or navigator.userLanguages (older IE) do not return a language.

To get your desired result order your browser languages by prio (drag&drop). Display google chrome in this language - does not have to do with the content shown on web - just sets prio for chrome itself.

**Comment by damienleroux** [comment]
I don't know another way than "Display google chrome in this language" for a user to change the default chosen language on newly loaded website. 

It appears to me than if I choose to display chrome in English, it is to see both chrome and websites in English.

How could a user change the website default computed language on first load otherwise?
I voluntary exclude the usual website top flag select :).

I think it make sense that when both `navigator.languages` and `navigator.language` are defined, with `navigator.language` contained in `navigator.languages`, `navigator.language` should be chosen first instead of the first valid/whitelisted `navigator.languages` element.

**Comment by jamuhl** [comment]
the order of the languages is relevant - on top is the most preferred - you can change the order by drag&drop

**Comment by jamuhl** [comment]
http://stackoverflow.com/questions/1043339/javascript-for-detecting-browser-language-preference

see answer with 129 upvotes

**Comment by damienleroux** [comment]
Thank you for the reference. It helped! [MDN](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/languages) declares that the order is relevant as well as Chrome in [their documentation](https://support.google.com/chromebook/answer/1059490?hl=en).I found the option "Display google chrome in this language" really misleading...

So I have to prey that my users read their browser documentation.. not like me!

**Comment by jamuhl** [comment]
agree on it to be missleading...hope they improve that...
