### ISSUE TITLE
Custom detector example

### ISSUE THREAD

**Issue by lopis** [i18next/i18next-browser-languageDetector#140]
I'm trying to add a detector because I only want to support some languages, for instance British English, but want to detect other english languages like 'en' and 'en-us'. I tried something like the following, but the this seems to have no effect at all. What am I missing? Is there an example of how `addDetector` should be used?

```js
  const lngDetector = new LanguageDetector()
  lngDetector.addDetector({
    name: 'customDetector',
    cacheUserLanguage(lng, options) {
      debugger
      if (lng.substring(0,2) === 'en')
        localStorage.setItem('i18nextLng', 'en_gb')
      else
        localStorage.setItem('i18nextLng', 'de_de')
    }
  })

  return i18n
   .use(lngDetector)
   .init(options)
```

**Comment by jamuhl** [comment]
you need to implement the detection function too: https://www.i18next.com/misc/creating-own-plugins.html#languagedetector

simpler would be using default detector and whitelist in options: https://www.i18next.com/configuration-options.html#languages-namespaces-resources 

-> whitelist
-> nonExplicitWhitelist

**Comment by lopis** [comment]
Thanks, that's what I was looking for.

**Comment by totymedli** [comment]
## Solution

I found out you also have to add your custom detector's name into the `detection.order` array. This is somewhy not mentioned in the [official readme](https://github.com/i18next/i18next-browser-languageDetector/blob/master/README.md). Without this, the detector will be never used.

Under the [detector options](https://github.com/i18next/i18next-browser-languageDetector/blob/master/README.md#detector-options) section, there is an example object that can be set as the `detection` property in the object you pass to `i18next.init()`. You should add the name of your detector (`customDetector`) to the property called `order` in that options object.

```js
i18next
  .use(LngDetector)
  .init({
    detection: {
      // order and from where user language should be detected
      order: ['customDetector', 'querystring', 'cookie', 'localStorage', 'navigator', 'htmlTag']
    }
  });
```

**Comment by totymedli** [comment]
Now this information is included in the [readme](https://github.com/i18next/i18next-browser-languageDetector/blob/master/README.md).
