### ISSUE TITLE
queryString lookupQueryString not picking up custom value

### ISSUE THREAD

**Issue by fouadmasoud** [i18next/i18next-browser-languageDetector#141]
detection: { // Settings for language detector
      order: ['querystring', 'cookie', 'navigator'],
      lookupQueryString: 'langPref',
      lookupCookie: 'myCookie',
      caches: ['cookie'],
      cookieMinutes: 525600
    }

Doesn't look like setting lookupQueryString actually works.

localhost:3000/?langPref=ja (Doesn't Work)

localhost:3000/?lng=ja (Works!)

I would expect the first one to work since I set lookupQueryString: 'langPref'

**Comment by jamuhl** [comment]
did you try `lookupQuerystring` lowercase s

**Comment by fouadmasoud** [comment]
oops that worked thanks! :D
