### ISSUE TITLE
Exclude Cache for querystring

### ISSUE THREAD

**Issue by fouadmasoud** [i18next/i18next-browser-languageDetector#142]
What value do I pass excludeCacheFor so that if the language is detected through querystring it's not stored as a cookie? I only see cimode as an example in the docs. Would be nice to expand on this so it's more clear on how to utilize this feature :)

**Comment by jamuhl** [comment]
it's to exclude languages not detection modes - that's why the sample has cimode as language -> as you probably do not want to cache that...

**Comment by fouadmasoud** [comment]
Is there a way to exclude caching if it's a querystring value?

**Comment by jamuhl** [comment]
no, sorry at time of caching we have no idea what source was used to detect...you would need to write a own override for the cookie detector not doing set cookie if value is in querystring:

https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/browserLookups/cookie.js#L44

adding using: https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/index.js#L43
