### ISSUE TITLE
Cant able to change Language which I am sending through query string

### ISSUE THREAD

**Issue by balajimitosis** [i18next/i18next-browser-languageDetector#145]
I am new to nodejs and i18next, I need to change the language based on user preference, am using node with express template.I used i18next-express-middleware for language detection but i was not successful.Thanks in advance

Server.js

'use strict';

import i18next from 'i18next';
const i18nMiddleware = require('i18next-express-middleware');
import i18nFS from 'i18next-node-fs-backend';
import i18nSprintf from 'i18next-sprintf-postprocessor';
import express from 'express';
import favicon from 'serve-favicon';
import methodOverride from 'method-override';
import cookieParser from 'cookie-parser';
import bodyParser from 'body-parser';
import cookieSession from 'cookie-session';
import errorHandler from 'errorhandler';
import passport from 'passport';
import logger from 'winston';
import expressWinston from 'express-winston';
import path from 'path';
import moment from 'moment';
import config from './config';
import routes from './backend/routes';
import db from './backend/models/db';

// Init locale
i18next.use(i18nMiddleware.LanguageDetector)
    .use(i18nFS)
    .use(i18nSprintf)
    .init({
        debug: false,
        fallbackLng: 'en',
        pluralSeparator: '_',
        keySeparator: '::',
        nsSeparator: ':::',
        detection: {
            order: [ /*'path', 'session',*/ 'querystring', 'cookie', 'header'],
            lookupQuerystring: 'lng',
            lookupPath: 'lng',
            lookupCookie: 'locaI18next',
            cookieDomain: 'loca',
            caches: ['cookie']
        },
        backend: {
            loadPath: path.join(dist_directory, 'locales', '{{lng}}.json')
        }
    });

// Init express
const app = express();
app.use(bodyParser.urlencoded({
    extended: true
}));
app.use(bodyParser.json());
app.use(methodOverride());
app.use(cookieParser());
app.use(cookieSession({
    secret: 'loca-secret',
    cookie: {
        maxAge: 3600000
    }
}));
app.use(i18nMiddleware.handle(i18next));
app.use(function(req, res, next) {
    var splitedLanguage = req.language.split('-');
    moment.locale(splitedLanguage[0]);
    next();
});

// Init routes
routes.forEach(route => {
    app.use(route());
});
 app.use(errorHandler());
 logger.info('In development mode (no minify/no uglify)');
}
db.init();
const http_port = process.env.LOCA_NODEJS_PORT || 8081;
app.listen(http_port, function() {
    logger.info('Listening port ' + http_port);
    if (debugMode) {
        const LiveReloadServer = require('live-reload');
        LiveReloadServer({
           _: ['dist'],
            port: 9091
        });
    }
});

Router.js
  router.get('/accounts',function(req, res){
       req.i18n.changeLanguage(req.query.lng);
     });

Kindly excuse me if I made some blunders, your help is  really appreciated.

**Comment by jamuhl** [comment]
would be great if you write what is not working...i guess

```
router.get('/accounts',function(req, res){
  req.i18n.changeLanguage(req.query.lng);
});
```

does not have translations loaded?!? on server you should preload every language: https://www.i18next.com/configuration-options.html#languages-namespaces-resources

```
i18next.init({ preload: ['en', 'de', '...'] });
```

**Comment by balajimitosis** [comment]
Thanks for the response,
Added preload in init

i18next.use(i18nMiddleware.LanguageDetector)
    .use(i18nFS)
    .use(i18nSprintf)
    .init({
        debug: false,
        fallbackLng: 'en',
        pluralSeparator: '_',
        keySeparator: '::',
        nsSeparator: ':::',
        detection: {
            order: [ /*'path', 'session',*/ 'querystring', 'cookie', 'header'],
            lookupQuerystring: 'lng',
            lookupPath: 'lng',
            lookupCookie: 'locaI18next',
            cookieDomain: 'loca',
            caches: ['cookie']
        },
        backend: {
            loadPath: path.join(dist_directory, 'locales', '{{lng}}.json')
        },
        fallbackLng: 'en',
        preload: ['en', 'fr', 'es']
    });
But not successful.
     Considering the route, am able to get language from the query string but i dont know how to apply that language, so that my EJS view changes( Though initially its able to detect the browser language and change ). 
      Currently am changing the language using jquery for translation in front end ( $('#signInEmail').html(i18next.t('E-mail')); ).But am forced to use timeout. thus for a fraction of sec, the browser language loads and then gets translated( which is really annoying ).

If you need any further information or any of my code.I will post.Thanks

**Comment by jamuhl** [comment]
so your problem is not related to the rendering on the server...but on client...

you init i18next on client too...use the callback there to render `i18next.init(options, () => { $('#signInEmail').html(i18next.t('E-mail')); })`

or bind the initialized event: https://www.i18next.com/api.html#oninitialized

**Comment by balajimitosis** [comment]
Yeah, I think so, I will try.Thanks
