### ISSUE TITLE
Validate language

### ISSUE THREAD

**Issue by moduval** [i18next/i18next-browser-languageDetector#148]
Since the querystring can be modified by a user, the plugin should validate if the detection is a valid language. If the language is not valid, we should go to the next detector.

**Comment by jamuhl** [comment]
Would be nice but i somehow lack of a good solution - how would you validate the language is valid?

**Comment by moduval** [comment]
Is there a list in i18next that list the configured language? Example, if I have fr and en configured and one of the detector return fr-CA, the language should be set to fr. If the language doesn't exist or is not configured, it should be set to the fallbackLng.

**Comment by jamuhl** [comment]
there is a whitelist feature...completely optional. there is additional a load option.

but all this gets decided after the basic language detection when i18next sets an array of language codes to load (lng-Region, lng, fallback)

i think simplest for you case would be creating a custom detector: https://github.com/i18next/i18next-browser-languageDetector#adding-own-detection-functionality taking the qs detector as base and do the additional valid check for your case.

**Comment by moduval** [comment]
Is the whitelist feature documented for this pluggin? If the language is not in the whitelist, what is the plugin doing ?

**Comment by jamuhl** [comment]
nope...whitelist is i18next option https://www.i18next.com/configuration-options.html#languages-namespaces-resources

**Comment by jamuhl** [comment]
you won't get that passed down to the detector code itself...that get only passed the detector options from the init options of i18next

**Comment by yannickl** [comment]
I have the same issue here. I've whitelisted the `en` and the `fr` language and when the navigator returns `fr-FR` the detector select the `en` language instead of the `fr`.

I've implemented a workaround for that, but as drawback we have to define all the language fallbacks in the options as following:
```javascript
i18next
  .use(LanguageDetector)
  .init({
    fallbackLng:  {
      'fr-BE': ['fr'],
      'fr-CA': ['fr'],
      'fr-CH': ['fr'],
      'fr-FR': ['fr'],
      'fr-LU': ['fr'],
      'fr-MC': ['fr'],
      'fr': ['fr'],
      'default': ['en'],
    },
    ns: ['common'],
    defaultNS: 'common',
    interpolation: {
      escapeValue: false,
    },
    resources: resources,
    whitelist: ["en", "fr"],
    nonExplicitWhitelist: true,
    detection: {},
  });
```
*Also not the use of `nonExplicitWhitelist` option.*

**Comment by jamuhl** [comment]
@yannickl if detection is fr-CA it will load and use fr-CA, fr, en if fallbackLng is 'en' -> https://jsfiddle.net/6v69fe9w/

can't really follow what you mean. If there is no fr translation it will use the en fallback

**Comment by jamuhl** [comment]
@moduval beside that whitelist is validated in detector (forgot about that): https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/index.js#L67

**Comment by jamuhl** [comment]
@yannickl i don't believe that. if detection (i18next.language) is fr-FR it will load and lookup per default in this order fr-FR -> fr -> en (fallback) ---> so 'en' will be only last option.

How do you come to the result it goes: fr-FR -> en ?? That's not possible if not set load: 'currentOnly' on init.

So basically what you want is:

```js
i18next
  .use(LanguageDetector)
  .init({
    fallbackLng: 'en',
    ns: ['common'],
    defaultNS: 'common',
    interpolation: {
      escapeValue: false,
    },
    resources: {
       en: { common: {  ...  } },
       fr: { common: {  ...  } },
    },
    whitelist: ["en", "fr"],
    nonExplicitWhitelist: true,
    load: 'languageOnly', // do not try to load fr-FR or en-US
  });
```

**Comment by jamuhl** [comment]
@yannickl can you create a reproducable jsfiddle or https://codesandbox.io/s/8n252n822 for react

**Comment by yannickl** [comment]
Indeed, this is my bad. The workflow works fine, I got lost in my mind trying to solve my issue... I'm sorry for the inconvenience. Thank you again for you quick help! 👍
