### ISSUE TITLE
Async Custom Language Detector

### ISSUE THREAD

**Issue by austrum** [i18next/i18next-browser-languageDetector#149]
Is it possible to have an asynchronous custom language detector? I need to call out to an API to get the user's stored locale preference, but since this is an async call, the value returned from my lookup function is null because the Promise returned from the API doesn't resolve until after the lookup call has completed. For now, I'm just calling the API directly and then calling i18n.changeLanguage once the Promise resolves (and not using a custom detector), but this causes the screen to flash briefly with my default language on first load. Any suggestions on how to work around this?

**Comment by austrum** [comment]
Great, thanks so much for pointing me in the right direction!

**Comment by brownbl1** [comment]
Looks like this is no longer available. Is there another documented example?

**Comment by jamuhl** [comment]
@brownbl1 the sample moved here: https://github.com/i18next/react-i18next/blob/master/example/v9.x.x/reactnative-expo/js/i18n.js#L7

**Comment by michaelg-hf** [comment]
Looks like the link isn't available anymore. Do you happen to still have an example? Thanks!

**Comment by adrai** [comment]
@michaelg-hf https://github.com/i18next/react-i18next/blob/v9.x.x/example/reactnative-expo/js/i18n.js
but for react-native use this one: https://github.com/i18next/react-i18next/blob/master/example/ReactNativeProject/i18n.js
