### ISSUE TITLE
detect language

### ISSUE THREAD

**Issue by ShintaroNippon** [i18next/i18next-browser-languageDetector#150]
Hello

I have this code 

```
import LanguageDetector from 'i18next-browser-languagedetector';


function getLanguage () {
    const i18n = localStorage.getItem('i18nextLng') && localStorage.getItem('i18nextLng').indexOf('pt') != -1
        ? require('./locales/pt/i18n').default
        : require('./locales/es/i18n').default
    return i18n;
}

export default getLanguage();
```

wich is a call to a different files es or pt
how can i detect language witho being with  localStorage.getItem('i18nextLng')
because on start application i got an error....

can someone help me on this
i want two differente files i18n configuration for each language

```
import { I18nextProvider } from 'react-i18next';
import i18n from '../../i18n';

```

many thanks carlos vieira

**Comment by ShintaroNippon** [comment]
what im trying to reach is a each resourse file for each language...

check please:


import i18n from 'i18next';
import XHR from 'i18next-xhr-backend';
import LanguageDetector from 'i18next-browser-languagedetector';
import { reactI18nextModule } from 'react-i18next';
import resourcespt from './translations.json'

i18n
  .use(XHR)
  .use(LanguageDetector)
  .use(reactI18nextModule) // if not using I18nextProvider
  .init({
    fallbackLng:  {
        'pt-PT': ['pt']
        },
    debug: true,

    interpolation: {
      escapeValue: false, // not needed for react!!
    },
    resources: resourcespt,
    // react i18next special options (optional)
    react: {
      wait: true,
      bindI18n: 'languageChanged loaded',
      bindStore: 'added removed',
      nsMode: 'default'
    }
  });

export default i18n;



it is another way to change resourcespt o es ?

**Comment by jamuhl** [comment]
adding translations on init via resources you can directly add both:

```js
//...
resources: {
  pt: require('./locales/pt/i18n').default,
  es: require('./locales/es/i18n').default
},
//...
```

You also can use: https://www.i18next.com/api.html#addresourcebundle

Or if on web use the xhr backend: https://github.com/i18next/i18next-xhr-backend

loading resources on demand is better than bundling all on initial start...
