### ISSUE TITLE
Fallback language not found with specific fallbackLng option

### ISSUE THREAD

**Issue by psavard** [i18next/i18next-browser-languageDetector#151]
Hello,

We are using a specific 'fallbackLng' configuration which looks like this 

`i18next.init({
    fallbackLng: { 
        'de-CH': ['fr', 'it'], 
        'zh-HANT': ['zh-HANS', 'en'],
        'es': ['fr'],
        'default': ['en']
    }
});`

This configuration should be supported as mentioned in the official i18n documentation : https://www.i18next.com/principles/fallback.html

But when I look at the code (see below), this specific configurations does not seem to be supported 
https://github.com/i18next/i18next-browser-languageDetector/blob/2b17200c2680c168a7484308cd294a6e2c8d90bc/i18nextBrowserLanguageDetector.js#L240

In my case, this specific line should be 

`return found || this.i18nOptions.fallbackLng[0] || this.i18nOptions.fallbackLng['default'];`

Is there any way we can support this?

Thank you very much

**Comment by jamuhl** [comment]
argh...i see...we missed that in this place (while we updated that in eg. the detector for express-middleware: https://github.com/i18next/i18next-express-middleware/blob/master/src/LanguageDetector.js#L71)

Will do an update asap.

**Comment by jamuhl** [comment]
should be fixed in i18next-browser-languagedetector@2.1.1

**Comment by psavard** [comment]
Thank you very much ;)

**Comment by Boscop** [comment]
What would be the correct way the fallback language to use when the language cookie is not set?
I looked here:
https://www.i18next.com/overview/configuration-options
https://www.i18next.com/principles/fallback
It says "`lng` - language to use (overrides language detection)", but I don't want to override language detection (from the cookie), so I shouldn't set `lng`.
But if I set `fallbackLng`, it will use this language as a fallback **on a per-key basis**, I don't want that.
Instead, I only want to fall back to a certain language *if and only if* the initial language detection (from the language cookie) fails.
How can I specify this? :)

**Comment by jamuhl** [comment]
fallbackLng will act as a fallback - not sure what you mean by on a per-key basis. If there is no cookie your i18next.languages will be set to whatever the fallback is -> means it will load the fallback and use it...as there is nothing else to use.

**Comment by adoyle-h** [comment]
@jamuhl The i18next.init option `fallbackLng` is not a fallback for what you mean.

>  it will use this language as a fallback on a per-key basis

It is right. Please read the document ["locals resolving"](https://www.i18next.com/principles/fallback#locals-resolving) once more.

I think it should be implemented with a `fallback` option in detector options.

**Comment by jamuhl** [comment]
fallback acts on a per key basis means if a key is not found in primary language it will take it from fallback - if found not. it still loads the complete namespaces for fallback lng. Acutally you can read i18next.languages and you get the ordered array of locales used.

**Comment by adoyle-h** [comment]
> fallback acts on a per key basis means if a key is not found in primary language it will take it from fallback - if found not. it still loads the complete namespaces for fallback lng. Acutally you can read i18next.languages and you get the ordered array of locales used.

Agree exactly. So that `i18nOptions.fallbackLng` is a fallback for i18next key resolving, not browser language detection.

Below is my scenario:

```js
import i18next from 'i18next';
import XHRBackend from 'i18next-xhr-backend';
import LanguageDetector from 'i18next-browser-languagedetector';
import {initReactI18next} from 'react-i18next';

const i18nextOpts = {
    debug: false,

    fallbackLng: ['common', 'en'],

    react: {
        useSuspense: false,
    },

    detection: {
        // I remove all detectors to make sure it will use the i18nOptions.fallbackLng
        order: [],
    },

    interpolation: {
        escapeValue: false,
    },

    backend: {
        // ...backend options
    },
};

i18next
    .use(XHRBackend)
    .use(LanguageDetector)
    .use(initReactI18next)
    .init(i18nextOpts);
```

I have pre-built three resource files: `zh-CN.json`, `en.json`, `common.json`. Like that:

```
// common.json
// All common translations will be put in common.json
{"common":{"button":{"english":"English", "chinese":"中文"}}}

// en.json
{"hello": "你好"}

// en.json
{"hello": "hello"}
```

It will support that,

```
// when i18next.language = "en"
i18next.t('hello') // => "hello"
i18next.t('common.button.english') // => "English"
i18next.t('common.button.chinese') // => "中文"

// when i18next.language = "zh-CN"
i18next.t('hello') // => "你好"
i18next.t('common.button.english') // => "English"
i18next.t('common.button.chinese') // => "中文"
```

Actually, when all detectors found nothing, it will return the i18nOptions.fallbackLng[0]. [Based this line](https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/index.js#L80).

```
i18next.language => "common"
i18next.languages // => ["common", "en"]
```

But the "common" is a resource name, not a browser language.

**Comment by jamuhl** [comment]
so do not fill `common` as a language...that's what namespaces are for.  https://www.i18next.com/overview/configuration-options#languages-namespaces-resources --> fallbackNS

https://www.i18next.com/principles/namespaces#sample

your files should have path/naming like: `/{lng}/{ns}.json`

**Comment by jamuhl** [comment]
for react also checkout the sample: https://github.com/i18next/react-i18next/tree/master/example/react

**Comment by adoyle-h** [comment]
`namespace` is common translations for a specific language. I need a common texts across multiple languages. Now I realize that it is not a i18n problem. It should be handled by myself. Thanks for your help. @jamuhl
