### ISSUE TITLE
Bug: Looking for subdomain in pathname

### ISSUE THREAD

**Issue by vadikace** [i18next/i18next-browser-languageDetector#157]
LanguageDetector searching for subdomain inside a pathname, in the _i18nextBrowserLanguageDetector.js[190:0]_. 
```javascript
var language = window.location.pathname.match(/(?:http[s]*\:\/\/)*(.*?)\.(?=[^\/]*\..{2,5})/gi);
```

I assume this regex should be executed on origin or href instead, right?

**Comment by jamuhl** [comment]
Would make sense i guess. @terhuerne do you agree or so i miss something?

**Comment by jamuhl** [comment]
sorry waited for a response...but published now: i18next-browser-languagedetector@2.2.1

**Comment by lucasdeassis** [comment]
@jamuhl It seems that the subdomain detector is still searching for `pathname` and not `origin` or `href` as @vadikace has mentioned. https://github.com/i18next/i18next-browser-languageDetector/blob/master/i18nextBrowserLanguageDetector.js#L193

**Comment by jamuhl** [comment]
@lucasdeassis could you recheck with i18next-browser-languagedetector@2.2.4

**Comment by lucasdeassis** [comment]
@jamuhl looks fine now. That subdomain detector works for websites like `https://fr.leagueoflegends.com`. How about a detector for sites like `https://www.amazon.ca/`? The challange would be that `ca` won't be a valid language code and I'm not sure if i18next would work fine. So It'd be necessary to have a dictionary like `ca: `en-CA` or something like that

**Comment by jamuhl** [comment]
@lucasdeassis think that is something we won't provide out of the box...in the end you can easily attach a detector doing this for your site: https://github.com/i18next/i18next-browser-languageDetector#adding-own-detection-functionality

**Comment by lucasdeassis** [comment]
Got it. Thanks @jamuhl

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:

**Comment by mattwr18** [comment]
@jamuhl could I ask you what the logic behind not supporting country specific domain detection is? Sorry, if it's obvious to others, but it's not to me... I also saw that we can add our own detection functionality, which is cool, but I was wondering if you could expand on the decision not to provide it out of the box. Thank you for your time and plugin.

**Comment by jamuhl** [comment]
country is not a language. what you set lng to in case of eg. swiss.ch?!? de, it, fr?!?

**Comment by mattwr18** [comment]
Thanks for the response @jamuhl ... I get that country is not a language, maybe there are more countries that one could not derive the language for than ones that one could, but I guess what I would expect is that the detector would return undefined and go to the next detector in the list.

I'm sure you have thought this through much more than me, and I think there are possibly lots of edge cases to consider so providing a way to add our own detector is probably a really good way to handle it. For Sweden, for example, the ccTLD is `.se`, but the language code is `sv`, so how should that be handled? Some sort of mapping? Also, there could be false detections where `eu` can be part of a domain, but it's also a language code for `Basque`
