### ISSUE TITLE
`cacheUserLanguage` is not being called after init or on the `changeLanguage` event in a custom language detector

### ISSUE THREAD

**Issue by Simill** [i18next/i18next-browser-languageDetector#160]
I'm trying to attach a custom language detector so I can cache the user language in Redux but it doesn't seem like my `cacheUserLanguage` event callback is ever getting triggered, though my initial `lookup` callback is.

Here's the relevant code:
```
const hxsbDetector = {
    name: 'hxsbDetector',
    lookup(options: DetectLanguage.DetectorOptions) {
        let browserLangCode = window.navigator.userLanguage ?
            window.navigator.userLanguage :window.navigator.language;        
        
        return browserLangCode;
    },
    cacheUserLanguage(lang, options) {
        // lang -> current language, will be called after init and on changeLanguage
        console.log('Hello from cacheUserLanguage! Language is %s', lang);
        // Add to redux here
      }
}

const languageDetector = new DetectLanguage(); 
languageDetector.addDetector(hxsbDetector);

const I18n = i18next
    .use(languageDetector)
    .init({
        detection: {
            order: ['hxsbDetector', 'navigator']
        },
       ...
});
```

Is there something else I'm missing?

**Comment by jamuhl** [comment]
did you call changeLanguage? only caches if changing from initial lookup -> there is no propagation to cache on init

**Comment by Simill** [comment]
Yes, I have a button that changes the language and it does successfully change it, but the cacheUserLanguage isn't called.

**Comment by jamuhl** [comment]
ah i see.

you did not add it to caches in detection options: https://github.com/i18next/i18next-browser-languageDetector#detector-options

**Comment by Simill** [comment]
Yup, that did it. Thanks!
