### ISSUE TITLE
Cache invalidation

### ISSUE THREAD

**Issue by dcworldwide** [i18next/i18next-browser-languageDetector#161]
How to invalidate the local storage cache?

My user accessed the app before I added their browser's default language. Now they see English instead of French.

**Comment by jamuhl** [comment]
Can you more explain what you mean by:

> My user accessed the app before I added their browser's default language. Now they see English instead of French.

How do you set the language?!?

**Comment by dcworldwide** [comment]
Not sure why the extra punctuation. 

I don't set it explicitly. I use this plugin to automatically detect the language. 

Scenario in detail:

- User accessed app before French translations existed.
- This plugin (or i18n-next react?) set a local storage prop (i18nextLng) to EN. 
- I deployed a new version of the app containing French translations
- The user still sees English.

So basically I have users who should now see French translations (because that is their navigator.language prop, but instead see English because of the LS i18nextLng prop.

**Comment by jamuhl** [comment]
Ah, i see. There is not much we can do in this case...it's just a detector and persisting mechanism. While there is an options expiration for cookies - there is nothing similar to localStorage. Also resetting that automatically might lead to more problems the road down as users might not won't that.

Like always the best option is to give your users an option to toggle that language - this way they can change the language anytime it gets added.

**Comment by ekryski** [comment]
> Like always the best option is to give your users an option to toggle that language - this way they can change the language anytime it gets added.

FWIW that's what we do @bidalihq.

You can also get them to manually run `localStorage.clear()` in their console. 🤷‍♂️

**Comment by strarsis** [comment]
For `react-query` I added the locale/language that is also sent to the API (`Accept-Language` HTTP request header) to the cache key (array). I hope this allows to easily invalidate the request caches when the locale is changed.
