### ISSUE TITLE
Question: Possible to redirect to another path?

### ISSUE THREAD

**Issue by Rzeszow** [i18next/i18next-browser-languageDetector#166]
Is it possible to automatically redirect to the page in the detected language?
English `domain/`
German `domain/de-DE/`
Italian `domain/it-IT/`

**Comment by jamuhl** [comment]
i18next is agnostic to your router implementation - use the `languageChanged` event to trigger such a route change: https://www.i18next.com/overview/api#onlanguagechanged

**Comment by Rzeszow** [comment]
Thanks
