### ISSUE TITLE
browser crash in chrome incognito window

### ISSUE THREAD

**Issue by nchang713** [i18next/i18next-browser-languageDetector#167]
i18n
.use(Backend)
.use(LanguageDetector)
.use(initReactI18next)
.init({
  ...
});

It seems chrome incognito window will keep loading constantly and make the browser crash.

**Comment by jamuhl** [comment]
had no issue with https://jsfiddle.net/jamuhl/ferfywyf/#tabs=js,result,html

**Comment by nchang713** [comment]
> had no issue with https://jsfiddle.net/jamuhl/ferfywyf/#tabs=js,result,html

Amazing..
It is my misunderstanding.
Thanks a lot.

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
