### ISSUE TITLE
Passing the detected language to the app

### ISSUE THREAD

**Issue by nerfologist** [i18next/i18next-browser-languageDetector#168]
Hello and sorry if this has already been explained but I couldn't find a proper way to achieve what I want.

I am using this great plugin to detect the user's language in my application, but there are several other things I need to set after detecting the language.

One example is globally setting `moment`'s locale:
```javascript
moment.locale(detectedLocale);
```

One more thing would be to store the detected language in the app's redux store:
```javascript
store.dispatch({ type: 'SET_USER_LOCALE', locale: detectedLocale });
```

If I try to read it from the `i18next.language`, as you suggested in #134, the language is not ready when I try to read it (so it returns undefined).

Is there a way to execute/run some code **after** the language is detected?

Thanks a lot in advance!

**Comment by jamuhl** [comment]
Use the callback or promise of the init call:

```js
i18next.init(options, () => { moment.locale(i18next.language); };

i18next
  .init(options)
  .then(() => { moment.locale(i18next.language); })
```

**Comment by nerfologist** [comment]
Thank you very much!
