### ISSUE TITLE
Why is en loaded when de is specified in url?

### ISSUE THREAD

**Issue by margozzi** [i18next/i18next-browser-languageDetector#169]
This is more of an optimization request I suppose. I was trying out the language detector and wanted to see the lng=de in action. I was surprised to see that the en was loaded before the de. The de strings were used correctly. I would rather the code not waste it's time loading the en strings when they are not going to be used.

Also, some example say show .use(LanguageDetector) and other .use(LngDetector). 

![image](https://user-images.githubusercontent.com/32365723/53972816-5f611680-40b4-11e9-97f1-b16ee5f6f2c9.png)

**Comment by jamuhl** [comment]
what gets load can be defined with options `whitelist`, `fallbackLng: false`, `load`

https://www.i18next.com/overview/configuration-options#languages-namespaces-resources
