### ISSUE TITLE
All supported languages

### ISSUE THREAD

**Issue by uluhonolulu** [i18next/i18next-browser-languageDetector#170]
I need the list of supported languages for my app's purposes. The Detector plugin does all the necessary job in the `detect` method, but then it just uses the first available entry, so the rest is lost.

It would be cool to extract the part that compiles the list of languages into a separate function if this information cannot be retrieved by other means.

I would be happy to submit a PR if you don't object.

**Comment by jamuhl** [comment]
can you describe your use case a little more...i18next does not support setting more than one language so returning the primary one is best done.

**Comment by uluhonolulu** [comment]
I'm creating a language learning application. For example, I have learning texts translated to French, German, and English, and LanguageDetector detects support for Spanish, Italian, and English. Then the primary language would be Spanish (no match), but if we look at the whole list we see that English is also a known language, so I can display the texts that have an English translation. If we detect Spanish, German, and English (in that order), then I'd preselect German (first match with my list), but also provide an option to select English. In any case, I assume that the list of languages that your code detects is what the user actually understands, from better to worse.

i18next has the `languages` property which would be cool to use, but it contains only the primary language and "dev" in my case.

**Comment by jamuhl** [comment]
The point is i18next cares for showing in one language -> the fallbacks you see in i18next.languages is only used in this order to fallback to them if a key was not found in primary language/locale.

In the end the only detector detecting multiple languages is order of priority is the navigator: https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/browserLookups/navigator.js

you can recreated that mapping against your priority list and add it back to detectors like: https://github.com/i18next/i18next-browser-languageDetector#adding-own-detection-functionality

**Comment by uluhonolulu** [comment]
Actually, everything I need is covered by the first half of the `detect` method (the one that calculates the `detected` array), no need to add another detector. Now I'm perfectly fine with copying that part in my code, but if you think it could be useful for others, I could make a PR. if not, please feel free to close this.

**Comment by jamuhl** [comment]
guess we can close this for now...if others request that too we can see to add something...but currently i guess it's more an edge case
