### ISSUE TITLE
querystring lookup failed when using hashrouter

### ISSUE THREAD

**Issue by zhaoyao91** [i18next/i18next-browser-languageDetector#172]
Everything goes well when I use BrowserRouter of the react-router. But when I switched to use HashRouter, it ignored the language specified in the querystring

**Comment by jamuhl** [comment]
hm...and why this is the fault of the detector?

**Comment by zhaoyao91** [comment]
detector may failed to detect querystring when using hash path

**Comment by jamuhl** [comment]
it can't https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/browserLookups/querystring.js#L8

if it does there is no querystring param...

**Comment by w3rdan** [comment]
Insert query string before hash path.
Example:
http://localhost:3000/?lng=pl&/#/your-hash-path

**Comment by jamuhl** [comment]
@w3rdan that looks not valid

**Comment by w3rdan** [comment]
@jamuhl 
I'm using react-router  (4.3.1) and eveything works fine.
I know it's looks weird at first glance :)

**Comment by jamuhl** [comment]
hm...detection depends on window.location.search...so i do not really see why the code should break in this case --> https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/browserLookups/querystring.js

anyway...PR welcome to fix this...

**Comment by w3rdan** [comment]
Wel.. I'm wokring now with app which is using react-router.

For such an URL:
http://localhost:3000/#/reports-summary?uuid=62090be2-8cd6-4aea-ba53-c028e373fbf8
window.location.search = ""

in component with router access:
this.props.location.search = "?uuid=62090be2-8cd6-4aea-ba53-c028e373fbf8"

-----
I put "lng" before hash path
http://localhost:3000/?lng=gb&/#/reports-summary?uuid=62090be2-8cd6-4aea-ba53-c028e373fbf8

window.location.search = "?lng=gb&/"

in component with router access:
this.props.location.search = "?uuid=62090be2-8cd6-4aea-ba53-c028e373fbf8"
ths same like in the 1st example.

**Comment by jamuhl** [comment]
@w3rdan and what should we do now...? only option would be adding a custom lookup that is compatible with react-router -> as it seems browsers can't handle those paths correctly...

**Comment by fuss86** [comment]
👍 for @w3rdan workaround.

Why is this issue closed ? 😃

**Comment by jamuhl** [comment]
@fuss86 we can reopen it...but does not change anything...still needs a PR

**Comment by fuss86** [comment]
So now there are open doors to fix it :) Maybe some contributor will be able to fix it

@w3rdan maybe ? 😃

**Comment by jamuhl** [comment]
I'm sure someone will do it - someone...someone...someone...did anyone see someone?

**Comment by w3rdan** [comment]
I think the best solution will be retrive query string directly from URL (without using document.location.[search|hash] fields)

```javascript
function getParameterByName(name, url) {
    if (!url) url = window.location.href;
    url = url.toLowerCase(); 
    name = name.replace(/[\[\]]/g, "\\$&").toLowerCase();
    var regex = new RegExp("[?&]" + name + "(=([^&#]*)|&|#|$)"),
        results = regex.exec(url);
    if (!results) return null;
    if (!results[2]) return '';
    return decodeURIComponent(results[2].replace(/\+/g, " "));
}

console.log(getParameterByName('lng', 'http://www.example.com/?lng=de'));
console.log(getParameterByName('lng', 'http://www.example.com/#/hash-router?lng=de'));
console.log(getParameterByName('lng', 'http://www.example.com/?lng=de&/#/hash-router'));
```

**Comment by jamuhl** [comment]
Now let's agree that not being able to use document.location.search is somehow - let's say - strange...

So, we could make this a custom lookup...https://github.com/i18next/i18next-browser-languageDetector#adding-own-detection-functionality in userland for those relying on hash based routing...?!?
