### ISSUE TITLE
Language not detected from navigator

### ISSUE THREAD

**Issue by mlimberg** [i18next/i18next-browser-languageDetector#174]
I have the following i18n config which was taken from this react [SSR example ](https://github.com/i18next/react-i18next/tree/master/example/razzle-ssr)

Language pref continues to be stored in localStorage though I read docs that indicate the `excludeCacheFor` should disable that and it doesn't update on refresh if the browser language preference (in the navigator) changes. Please help! I've tried many alterations (including putting the order in a `detection` prop. Any advice is greatly appreciated!

```javascript
import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'
import XHR from 'i18next-xhr-backend'
import LanguageDetector from 'i18next-browser-languagedetector'

const options = {
  fallbackLng: 'en',
  ns: ['translations'],
  defaultNS: 'translations',
  order: ['navigator'],
  debug: true,
  caches: [],
  excludeCacheFor: ['cimode'],
  interpolation: {
    escapeValue: false, // not needed for react!!
    formatSeparator: ',',
    format: (value, format, lng) => {
      if (format === 'uppercase') return value.toUpperCase()
      return value
    },
  },
  react: {
    useSuspense: false,
  },
  detection: {
    order: ['navigator', 'cookie'],
  },
  wait: process && !process.release,
}

if (process && !process.release) {
  i18n
    .use(XHR)
    .use(initReactI18next)
    .use(LanguageDetector)
}

if (!i18n.isInitialized) {
  i18n.init(options)
}

export default i18n
```

**Comment by jamuhl** [comment]
excludeCacheFor takes an array of languages where it should not store it (cimode is a i18next language used for returning keys during ci runs)

caches: [] should be sufficient to not persist language changes

**Comment by mlimberg** [comment]
Hmm I added `caches: []` to both the client and server i18n instance and it's still saving to localStorage on initial page load

**Comment by jamuhl** [comment]
really got the feeling your setup has some serious flaws.

https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/index.js#L93 -> no caches set there won't be anything storing that value to localStorage...

**Comment by nilamsavani** [comment]
@jamuhl  @adrai Do you have any example where language detection based on  browser is working perfectly?

**Comment by adrai** [comment]
@nilamsavani I don’t know what you mean by perfectly, but: https://codesandbox.io/s/react-i18next-example-5w0ny?file=/src/i18n.js

Btw: For general questions please go to StackOverflow... 
if you have an issue with a specific library and have no solution for it, create an issue on GitHub with a reproducable example.
Asking questions not really related on already closed issues is not best practice on GitHub, thx.

**Comment by nilamsavani** [comment]
@adrai Thanks, will keep in mind. 

This demo is fine but it is not automatically detecting language. We have to click on button.

Clarification: Someone open my application in browser with language as `en` then translations for that should render and if someone open application in browser with language `de` then translations for that should render.

**Comment by adrai** [comment]
@nilamsavani This is exactly what this does... based on the browser language...

Create a reproducable example and open a new issue uf needed.
