### ISSUE TITLE
How about onlyLang settings

### ISSUE THREAD

**Issue by neic89** [i18next/i18next-browser-languageDetector#175]
I need in only a lang, without region. Example: en-EN -> en, fr-FR -> fr.
How i can do it?

I think need add setting onlyLang. If this setting is true, then return only lang.

Thanks for answer.

**Comment by jamuhl** [comment]
the detector will always return full qualified locale.

you can set `load: 'languageOnly'` in i18next init to only allow root languages without region

**Comment by neic89** [comment]
Oh...
I have to use substr (0,2) to get only the language in my components, but this is a potential error for other developers (they can simply forget or not take this moment into account).
I plan to trim the entire locale and get only the language before rendering the application in index.js. Just by writing this code: i18next.changeLanguage (i18next.language.substr (0,2))

This may be a precursor of the mistakes I mentioned above.
I think it would still be nice to add this setting. Or is this a limitation of the i18-text itself?

**Comment by jamuhl** [comment]
Like said...the official way is to set `load: 'languageOnly'` and use `i18next.languages[0]` for getting the first language used for a translation key lookup

**Comment by Komalov** [comment]
```
i18next
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    debug: false,
    nsSeparator: false,
    keySeparator: false,
    fallbackLng: false,
    load: 'languageOnly',
    resources,
  });
```
`i18n.language` will be full lang like `en-US` till I manually trig `i18n.changeLanguage`. It's super counterintuitively that i18next does exactly opposite to config.

**Comment by jamuhl** [comment]
Idk...i18next does persist the most exact locale - but does not the "opposite" -> it loads only the languages (therefore the load option) from the backend and only resolves translations from the locale stripped the region...

i18next.language -> detected most precise locale
i18next.languages -> used languages in order of priority
