### ISSUE TITLE
Configure routes when using path detection

### ISSUE THREAD

**Issue by corand** [i18next/i18next-browser-languageDetector#176]
I can make the app choose the correct language based on the language specified on the path. Exmple: `localhost:3000/en/home` or `localhost:3000/es/home`. My problem is that /home route is not recognize and a 404 is rendered. What is the correct way to configure this? and what if I want to be `localhost:3000/home` (en) and `localhost:3000/es` (spanish)?

**Comment by jamuhl** [comment]
browser language detection is in browser -> how can you get a 404 ? do you use this on serverside?!?

normally i would say home -> no language detected -> it will use fallbackLng (en)

**Comment by corand** [comment]
`
<Router>
          <Switch>
            <Route exact path="/" component={Home} />
            <Route path="/contact" component={Contact}/>
            <Route component={NotFoundPage} />
          </Switch>
        </Router>
`

With 404 I mean that the route does not match with any configured on routes, so it renders `NotFoundPage`. With this configuration I am able to display the main page, but if I put the language in the path for any of the pages, it does display the `NotFoundPage`. But the language detection works fine.
- localhost:3000/contact: works fine. Contact page in english.
- localhost:3000/es/contact: not found page displayed in spanish

**Comment by jamuhl** [comment]
```js
<Router>
      <Switch>
        <Route exact path="/" component={Home} />
        <Route path="/contact" component={Contact}/>
        <Route path="/es/contact" component={Contact}/>
        <Route component={NotFoundPage} />
      </Switch>
 </Router>
```

works....right?

**Comment by corand** [comment]
Yes. Ok, so I need tu duplicate each path for each language. Is that the correct way to do it?

Thankyou! :)

**Comment by jamuhl** [comment]
I wouldn't duplicate it for every language but do something like `<Route path="/:lng/contact" component={Contact}/>` or even better create some `LocalizedRoute path="/contact" component={Contact} />` -> which will have both the `<Route path="/contact" component={Contact}/>` and `<Route path="/:lng/contact" component={Contact}/>`

and i would replace `:lng` with a regex against a whitelist of languages if the router supports regex there...
