### ISSUE TITLE
Options is missing custom getCookie and setCookie

### ISSUE THREAD

**Issue by ImanMh** [i18next/i18next-browser-languageDetector#178]
How i18next-browser-languageDetector is able to get and set cookies on an express server?
I would like to have your opinion for a PR that adds getCookie and setCookie options to this package so I can store and retrieve user preferred language on server as well.

**Comment by jamuhl** [comment]
express ---> https://github.com/i18next/i18next-express-middleware#language-detection comes with a fully implemented serverside language detector

**Comment by ImanMh** [comment]
Thanks.
