### ISSUE TITLE
Argument of type 'typeof I18nextBrowserLanguageDetector' is not assignable 

### ISSUE THREAD

**Issue by mhjadav** [i18next/i18next-browser-languageDetector#179]
After upgrading to latest version getting error 

Argument of type 'typeof I18nextBrowserLanguageDetector' is not assignable to parameter of type 'BackendModule | LoggerModule | LanguageDetectorModule | LanguageDetectorAsyncModule | I18nFormatModule | ThirdPartyModule[]'.
  Type 'typeof I18nextBrowserLanguageDetector' is missing the following properties from type 'ThirdPartyModule[]': pop, push, concat, join, and 25 more.ts(2345)

Will you guys please look into this at earliest
<img width="1291" alt="Screenshot 2019-07-31 at 12 57 28 PM" src="https://user-images.githubusercontent.com/6236090/62192339-0d869900-b393-11e9-981f-4d2763f579b2.png">

**Comment by XmlmXmlmX** [comment]
same for me

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/pull/1291

**Comment by bodograumann** [comment]
Works for me with the latest version!
