### ISSUE TITLE
My language detector not working

### ISSUE THREAD

**Issue by hrahimi270** [i18next/i18next-browser-languageDetector#183]
I did just like the example in [documents](https://react.i18next.com/legacy-v9/step-by-step-guide#c-auto-detect-the-user-language).
This is a screenshot of my code:

<img width="595" alt="Screen Shot 2019-08-10 at 12 04 59 PM" src="https://user-images.githubusercontent.com/38007163/62819193-36631700-bb67-11e9-989d-ce36eb619ec1.png">

As you can see, I set `lookupLocalStorage` to **language**, not the default value.
But I test it with the default value.
I also clear my localStorage once.
I have no idea why it doesn't work!

Note: In the example used `reactI18nextModule` for init the i18next but it's not exported from it!

**Comment by jamuhl** [comment]
should work: https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/browserLookups/localStorage.js#L18

but you hardcode lng to "en" not running the detector

setting lng=en on init does just fix lng to en omitting the detector
