### ISSUE TITLE
SSR - detection on server side is different than on client side

### ISSUE THREAD

**Issue by dawidskowron** [i18next/i18next-browser-languageDetector#185]
Hello,
I don't know it's an issue but I got stuck, maybe someone will help me.

I have 2 languages on the page. The default is set as 'en' using **fallbackLng**.

```
import i18n from 'i18next';
import detector from 'i18next-browser-languagedetector';
import { initReactI18next } from 'react-i18next';

import translationEN from '../translations/en/translation.json';
import translationPL from '../translations/pl/translation.json';

const resources = {
    en: {
        translation: translationEN
    },
    pl: {
        translation: translationPL
    }
};

i18n
    .use(initReactI18next)
    .use(detector)
    .init({
        detection: {
            lookupLocalStorage: 'language',
            order: ['path'],
            lookupFromPathIndex: 0
        },
        resources,
        debug: true,
        caches: [],
        fallbackLng: 'en', // use en if detected lng is not available
        keySeparator: false, // we do not use keys in form messages.welcome
        whitelist: ['en', 'pl'],
        load: ['en', 'pl'],
        interpolation: {
            escapeValue: false // react already safes from xss
        }
    });
	
export default i18n;
```

I try to detect language by path:
- https://localhost:3000/ - detected **en** on client and server side
- https://localhost:3000/**pl/** - detected **pl** on client side but on server side it's "en" even when the browser is reloaded.

It's ok that on server side I have always "en" ?

**Comment by jamuhl** [comment]
do you SSR? do you use next-i18next? next.js?

`load: ['en', 'pl']` -> there is no load option!!!

this detector does not work on serverside! -> https://github.com/i18next/i18next-express-middleware#language-detection

**Comment by dawidskowron** [comment]
Yes, I use next.js and next-i18next

So, it's ok that I have always "en" on server side.
Thank you for the link, I will try to use it.

**Comment by jamuhl** [comment]
It's not optimal SSR will render "en" -> client eventual "pl" ---> mismatch of content (next will complain) -> you will need to detect on serverside too
