### ISSUE TITLE
caches option works weird

### ISSUE THREAD

**Issue by DmitryVolkovTulaco** [i18next/i18next-browser-languageDetector#186]
I have the following configuration for i18n
```javascript
order: ['navigator', 'querystring'],
    lookupQuerystring: 'lng',
    caches: [],

    fallbackLng: 'en',
    debug: true,
    ns: ['translations'],
    defaultNS: 'translations',
    keySeparator: false,
    interpolation: {
        escapeValue: false,
    },
```
Library adds i18nextLng variable in localStorage on page load, and after switching language using queryString param, it is saved to localStorage. After refreshing the page I see language from localStorage, not from navigator, what I'm doing wrong?

**Comment by jamuhl** [comment]
? no caches set nothing will be saved...if you got a value in localStorage it's from a old request or done by something else but not the detector...

it loads in order set in order...there is no magic...

**Comment by DmitryVolkovTulaco** [comment]
Restarted project, closed all tabs, cleaned up localstorage, made hard reload, what else should I do?

**Comment by DmitryVolkovTulaco** [comment]
Tried to update config a bit 
```
order: ['localStorage', 'navigator', 'querystring'],
lookupQuerystring: 'lng',
lookupLocalStorage: 'vwt-dev-manager-lng',
caches: [],
```

but in my localStorage I still see i18nextLng variable

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/index.js#L93 ---> there is no save if not set so...what should i say...can't debug your code for you
