### ISSUE TITLE
Custom Async locale detector

### ISSUE THREAD

**Issue by techterbium** [i18next/i18next-browser-languageDetector#188]
I am using below configuration to set the locale of the app by asynchronously detecting the locale of the user:

`import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import { getUserLocale } from "../../utils/users"

import enUS from './locale-en-US';
import spanish from './locale-es';

const resources = {
  en: enUS,
  en_US: enUS,
  es: spanish,
};

const customLanguageDetector = {
  type: "languageDetector",
  async: true,
  detect: callback => {
    // callback("en_US");                      //This is working
    return getUserLocale().then(locale => callback(locale));        // This is NOT working.
  },
  init: (parms) => {  },
  cacheUserLanguage: (locale) => { }
};

i18n
  .use(initReactI18next) // passes i18n down to react-i18next
  .use(customLanguageDetector)
  .init({
    resources,
    load: 'languageOnly',
    interpolation: {
      escapeValue: false, // react already safes from xss
    }
  });

export default i18n;
`

In the 'detect' method, directly calling the callback with the locale is working. However, calling callback from a promise is not working. Any help here is much appreciated.

**Comment by jamuhl** [comment]
async detectors work..that is tested....as you provide a custom detector not using the detection options you do not have to pass them...

the only problem I can spot from just reading that code you provided is - do not use en_US but en-US

**Comment by techterbium** [comment]
Thank you @jamuhl  for your swift response. I have removed detection options (and updated my comment above). However, it still doesn't work. 

I do not have control over what comes out of `getUserLocale()` method. Currently, I see 'en_US' as value for the locale. Hence, I am maintaining the `resources` mapping of locale keys to the language that needs to be used. 

The point where I got stuck is - calling `callback("en_US")` directly from 'detect' method works. However, when calling the `callback(locale)` from promise's then method is not working. Thank you for your help here again.

**Comment by jamuhl** [comment]
i18next will split based on `-` to eg. fallback to `en` as needed...might not be related right now...but I promise you will run into problems using the `_`. (using string replace _ with - would solve this)

https://github.com/i18next/i18next/blob/master/src/i18next.js#L249 as you see the code is simple...there can be no difference if calling callback directly or in the promise...the only thing different is timing

So please describe your doesn't work:
- Does it render before language was set?

**Comment by techterbium** [comment]
Yes, its rendering before language is set. I had `alert` statement in `getUserLocale()` method and I see that UI is already visible with OUT language is set. 

To avoid confusion around `_` & `-`, I am setting the locale as below. 
` getUserLocale().then(function (locale) {alert(locale); callback(locale.substring(0, 2)) })
//alerts "en_US"
`

**Comment by jamuhl** [comment]
Ok, then we got no issue with detection...that is working fine...

The problem is rendering. But react-i18next suspense rendering when i18next not initialized yet (not run through detector / initialization): https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js#L40

Do you use useTranslation hook or withTranslation HOC?

**Comment by techterbium** [comment]
I may sound little odd here, but I was not using either of `useTranslation` or `withTranslation`.
I was using `t` function provided by i18n object exported from code mentioned in my first comment above. 

I just started using `withTranslation` HOC for my home/main component as mentioned [here](https://react.i18next.com/latest/withtranslation-hoc). However, I am seeing below error in my console. Not sure what is going wrong here.

![image](https://user-images.githubusercontent.com/4904359/65414634-c0162d80-de11-11e9-9d97-1e781158f65f.png)

**Comment by jamuhl** [comment]
on what react version are you? https://github.com/i18next/react-i18next#requirements

**Comment by techterbium** [comment]
Thank you @jamuhl  for your guidance all the way thru. I was not properly using i18next in my react components properly. And also, as you rightly pointed out, I am not using recommended versions of react in my project. 

After correcting the above issues, I am now able to see the right language is set in the react components and everything is working as expected. Thanks for your help.

**Comment by jamuhl** [comment]
good to see this one solved...
