### ISSUE TITLE
3.1.0 appears to break our whitelist

### ISSUE THREAD

**Issue by redbugz** [i18next/i18next-browser-languageDetector#191]
This morning our whitelist stopped working, and i18n.language is now returning 'en-US' instead of 'en' which we have in our whitelist.

I haven't had time to dive in and investigate. We are pinning back to 3.0.x to fix it.

I'm assuming it has to do with this change, but haven't confirmed cause yet.

Our config:
```
import supportedLocales from './supportedLocales'
...
i18n.init({
...
      whitelist: supportedLocales,
...
```

**Comment by jamuhl** [comment]
can you try: i18next-browser-languagedetector@3.1.1
