### ISSUE TITLE
Detector to search only for language without code

### ISSUE THREAD

**Issue by bologer** [i18next/i18next-browser-languageDetector#195]
Great library! 

Is it possible to detect language and then define how detected language would be stored? 

We use language only (e.g. en) without region - and it works great. But when language is being detected, it is stored as en-US.

**Comment by bologer** [comment]
@jamuhl I mean more about some kind of transform option to the detected language

**Comment by bologer** [comment]
I defined `languageOnly` in options of react-18next, meaning I have `en` only instead of `en-US`. I use user selected language in language dropdown (with flags, etc) and expect to have just language without region. 

Language detector stores language with region, which breaks application logic. Currently I have work around to cut language if it is bigger then 2 chars.

**Comment by gregbown** [comment]
@bologer [working example](https://gist.github.com/gregbown/1b02096766606b6d80703a6c416c1ea5) using "en"

**Comment by angrybacon** [comment]
Is there a way to have the local saved in the local storage be plain with no region code?

The following configuration finds `'en-en'` and saves it under the specified name. This forces me to sanitize it in my getter.

```js
import i from 'i18next';
import BrowserLanguage from 'i18next-browser-languagedetector';
import Backend from 'i18next-xhr-backend';
import { initReactI18next } from 'react-i18next';

i.use(initReactI18next).use(Backend).use(BrowserLanguage).init({
  backend: {loadPath: 'locales/{{lng}}/{{ns}}.json'},
  cleanCode: true,
  debug: false,
  detection: {
    lookupCookie: Cookie.names.locale,
    lookupLocalStorage: Local.names.locale,
    lookupQuerystring: 'language',
    order: ['querystring', 'localStorage', 'navigator', 'htmlTag', 'path', 'subdomain'],
  },
  fallbackLng: 'en',
  interpolation: {escapeValue: false},
  load: 'languageOnly',
  lowerCaseLng: true,
  react: {useSuspense: false},
  returnObjects: true,
});
```

**Comment by adrai** [comment]
I don’t think so... probably only with a custom language detector...
But why?

**Comment by angrybacon** [comment]
@adrai Why what specifically? The region code is just noise in my case.

**Comment by adrai** [comment]
For i18next and this plugin it’s ok to have it like this: en-US...
So either you write your own language detector or continue with your workaround. 🤷‍♂️

**Comment by angrybacon** [comment]
@adrai How is ok when I'm apparently not the only to expect `load: 'languageOnly'` to have a different behavior?
I guess a better question is: "What does justify the saving not taking into acount this `load` option?"

**Comment by adrai** [comment]
Seems it was designed like that.
languageOnly is a load option of i18next.
And this is a language detector plugin.
Feel free to submit a PR so it can be discussed.

**Comment by angrybacon** [comment]
Yeah this looks like the plugin's responsibility, who is the one doing the saving in the first place if I'm not mistaken. Thanks for the clarification :-)

**Comment by jamuhl** [comment]
yes...the detector detects and saves the locale detected while i18next will further process that to just use the language part or whitelist,...

the reason for this is - when you decide in future to change that, or add new languages i18next has the raw detected value and can decide optimal given the new settings...

**Comment by Amine27** [comment]
This cause a 404 error for language with code not found by the web server!

**Comment by adrai** [comment]
@Amine27 can you please give more information? A reproducable example?
I don’t know what you mean...

**Comment by Amine27** [comment]
Well, I am using `load: 'languageOnly'` as setting, and provide language without local (eg: `en`, `ar`). The detector returns `en-US` and the i18next library search for this file on the system, my web server (nginx) return a 404 error (file not found). Then i18next fallback to `en` file.

My problem is: I do not want this 404 error (for SEO things). So, can this plugin returns only language part without local if `load: 'languageOnly'` is set ?

**Comment by adrai** [comment]
Just to be sure:
Load is set to languageOnly
and the whitelist is set to an array containing all your served languages?

**Comment by Amine27** [comment]
Here is my configuration:

```
  i18next
    .use(i18nextHttpBackend)
    .use(i18nextBrowserLanguageDetector)
    .init({
      debug: true,                                                                                                                                                      
      load: 'languageOnly',
      fallbackLng: 'en',
      whitelist: ['en', 'ar', 'fr'],
      backend: {
        loadPath: 'locales/{{lng}}.json',
        addPath: 'locales/{{lng}}.missing.json'
      }
    }, (err, t) => {
      jqueryI18next.init(i18next, $)
      $('body,html').localize()
    })
```
And my nginx log:
`[error] 6#6: *9 open() "/usr/share/nginx/html/locales/en-US.json" failed (2: No such file or directory)`
I am using the `i18next@19.4.4`, `jquery-i18next@1.2.1`, `i18next-http-backend@1.0.8` and `i18next-browser-languagedetector@4.1.1`.

**Comment by adrai** [comment]
Sorry, can't reproduce this.
Can you try to create a codesandbox example, like this: https://codesandbox.io/s/react-i18next-example-5w0ny?file=/src/i18n.js

**Comment by Amine27** [comment]
Well, the 404 error was caused by another function and not i18next (sorry for that!).
I ended up manually splitting the language part (without locale) from the detected language, and no errors so far.
Thank you for your time.
