### ISSUE TITLE
Universal language detector

### ISSUE THREAD

**Issue by Vadorequest** [i18next/i18next-browser-languageDetector#196]
Just wanted to let you know that we released a universal language detector that is based on this library :)

https://github.com/UnlyEd/universal-language-detector

I don't know if that's something that could/should be added to the doc, it would be useful in particular for people using universal frameworks such as Next.js

Well, at least I know I'd loved to find something similar when getting started with i18next, because there isn't any lib out there that supports universal language detection (AFAIK)

**Comment by jamuhl** [comment]
nice...feel free to add it to the list here: https://www.i18next.com/overview/plugins-and-utils#language-detector so others can find it...

**Comment by Vadorequest** [comment]
Thank you for the tip! It's done :)

https://github.com/i18next/i18next-gitbook/pull/108

**Comment by jamuhl** [comment]
was merged...thank you
