### ISSUE TITLE
Typescript error when using DetectorOptions

### ISSUE THREAD

**Issue by Janaka-Steph** [i18next/i18next-browser-languageDetector#197]
Hello,

I have a Typescript error when using DetectorOptions:
`Object literal may only specify known properties, and 'lookupFromPathIndex' does not exist in type 'DetectorOptions'.`

Indeed 'lookupFromPathIndex' is not specified in index.d.ts. 
Any reasons for that?

**Comment by jamuhl** [comment]
Feel free to provide a PR.
