### ISSUE TITLE
How to use lng-region despite lng only was detected

### ISSUE THREAD

**Issue by egorlitsky** [i18next/i18next-browser-languageDetector#198]
Hi everyone,

I use i18next + languageDetector as follows

```
const conf = {
    debug: false,
    initImmediate: true,
    fallbackLng: 'en-US',
    ns: ['lang'],
    interpolation: {
        prefix: '__',
        suffix: '__'
    },
    backend: {
        loadPath: 'locales/__lng__/__ns__.json'
    },
    react: {
        wait: true
    },
    detection: {
        order: ['navigator', 'querystring', 'cookie', 'localStorage', 'htmlTag']
    }
};


i18n.use(XHR)
    .use(LanguageDetector)
    .init(conf);
```

Our back-end uses lng-region resource directories `en-US`, `ru-RU` etc. - there are no `en`, `ru`.
But Chrome and Firefox always report Russian language as `ru` -> languageDetector selects `ru` as `found`, so it will load `ru`. 

Yes, I could use `fallbackLng` kind of {ru: ['ru-RU']} and the correct resources will be loaded, but `i18nextLng` in local storage will be still `ru` and that's the problem...

The behavior I'm looking for:
1) `ru-RU` resources will be loaded even if `ru` is set as the most priority browser language
2) `i18nextLng` in local storage will be `ru-RU` to be consistent with actual loaded resources

I understand that the current languageDetector's behavior functions as designed, but how can I solve the issue with inconsistent `i18nextLng`?

Could you point me to the proper config or logic, please? Thanks in advance!

**Comment by jamuhl** [comment]
the only option I could think of is creating a custom language detector: https://www.i18next.com/misc/creating-own-plugins#languagedetector as basically mapping a pure language to a locale containing a region is not the common case and actually can't be done automatically (as there is not such a 1 to 1 mapping)

Beside having the detector mapping lng to lng-REGION you might also have to set `load: currentOnly` to avoid loading the lng file

**Comment by egorlitsky** [comment]
@jamuhl thanks for the quick response!
Actually I've already tried this approach today and it works fine. Moreover, your answer confirmed this. Thanks again and feel free to close the issue.

Regards,
Vladislav

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

If you liked my support / work - I would enjoy a coffee sponsored using the “:purple_heart:Sponsor Button”.

There are many ways to help this project :pray:
