### ISSUE TITLE
Index file points to non-existent commonjs file in dist folder

### ISSUE THREAD

**Issue by Crecket** [i18next/i18next-browser-languageDetector#199]
When installing the package there is a index.js which seems to get used in some installations over the file defined as "main" in the package.json file. That index file contains `require('./dist/commonjs/index.js').default;` which isn't an existing file resulting in a file not found error.

I assume this is left over from an older version or a file hasn't been published correctly.

**Comment by jamuhl** [comment]
good catch - fixed in i18next-browser-languagedetector@4.0.2
