### ISSUE TITLE
v4 adds entire @babel/runtime library

### ISSUE THREAD

**Issue by AStoker** [i18next/i18next-browser-languageDetector#200]
Looks like this [commit](https://github.com/i18next/i18next-browser-languageDetector/commit/4113fdb144f7202ac63947a0e57ef2b82ab7423e#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R19) added @babel/runtime to the list of dependencies. This is a rather large addition to this library (about 90kb), and when bundlers go through and trace dependencies, it includes babel/runtime.
Something simple like browser language detection shouldn't require an entire babel/runtime library to be included. Was this done in error (my guess)? It's likely that during the compiling process of this library it's adding babel/runtime.

**Comment by jamuhl** [comment]
em...the runtime is 3kb - is also included in https://bundlephobia.com/result?p=i18next 

actually this should reduce the size of the final bundle...as it's treeshakable and imported only once:

sample dist file:

```js
import _classCallCheck from '@babel/runtime/helpers/esm/classCallCheck';
import _createClass from '@babel/runtime/helpers/esm/createClass';

var arr = [];
var each = arr.forEach;
var slice = arr.slice;
function defaults(obj) {
// ...
```

**Comment by AStoker** [comment]
I apologize for any confusion this might have brought up. I think something weird was happening with the bundler and tracer. It was pulling in a massive version of the babel runtime, which also ended up pulling in a bunch of libraries it shouldn't have (stream, base64,...). My guess is it was somehow pulling in the source version instead of the dist version. I'll close this out.

**Comment by jamuhl** [comment]
Nothing to worry...glad you brought this up...if there is something wrong...it should be fixed. Glad it seems all ok now.

If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

If you liked my support / work - I would enjoy a coffee sponsored using the “:purple_heart:Sponsor Button”.

There are many ways to help this project :pray:
