### ISSUE TITLE
"navigator" resolver not working properly when device uses "en-US" format

### ISSUE THREAD

**Issue by Vadorequest** [i18next/i18next-browser-languageDetector#201]
I just encountered a very peculiar bug. It's related to the `navigator` resolver.

```
// Browser
navigator.languages
["en-US", "fr-FR", "fr", "en"]
````

Calling `i18nextUniversalLanguageDetector.detect()` will return `fr`, instead of `en`, because it ignores "en-US" and "fr-FR" somehow. (it's an instance of `i18next-browser-languagedetector`)

See https://github.com/UnlyEd/universal-language-detector/blob/1e801b8965a904babd88c7655c99f63f8bba7b8a/src/index.ts#L105

This causes an issue with our universal-language-detector, because it detects a different language whether using SSR or CSR, the user first sees the page in english (SSR), and then in french (CSR).

Is it a misconfiguration on our side? Or a bug?

**Comment by jamuhl** [comment]
the detector for navigator https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/browserLookups/navigator.js returns all lngs in that array -> but will use the first if no whitelist or whitelisted: https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/index.js#L70

i18next.language should be set to that value -> i18next.languages[0] can be different again based on load options

**Comment by jamuhl** [comment]
So in your case, it's a result of the whitelist set

**Comment by jamuhl** [comment]
set https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/index.js#L73 `checkWhitelist` to false in the init options of detector should change to the behaviour you like.

**Comment by Vadorequest** [comment]
I see, thank you!

I'd still like to use the whitelist though, because otherwise I'll have to implement that behaviour myself.
Do you think the usage of some pattern could be benefical in the `whitelist`? 
I'm thinking about `['en', 'en*']` for instance. Or maybe some whitelist-related option?

What do you think?

**Comment by jamuhl** [comment]
a) there is the `checkWhitelist` option in the detector
b) there is the `nonExplicitWhitelist` option in i18next https://www.i18next.com/overview/configuration-options#languages-namespaces-resources

**Comment by Vadorequest** [comment]
Awesome. Gonna try this right away, it's exactly what I needed.
