### ISSUE TITLE
what is the   code used by this package?

### ISSUE THREAD

**Issue by AronWater** [i18next/i18next-browser-languageDetector#204]
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

may I know what is the standard code format used?

**Comment by jamuhl** [comment]
When the browser makes a request, language and locale are returned as simple two-letter ISO codes (ISO-3166 and ISO-639), which together indicate the language and country variant of that language; for example en-GB for English as used in the UK. There are currently 249 country codes set out in ISO-3166 and 184 languages defined in ISO-639.
