### ISSUE TITLE
Specify language resolution order or a preferred language

### ISSUE THREAD

**Issue by morinted** [i18next/i18next-browser-languageDetector#212]
## 🚀 Feature Proposal

Match the "best" language before falling back to other translations.

## Motivation

Target providing the application in certain languages.

## Example

Say user's browser languages are [French, English, Japanese].

Application is written in English-first for an English market, but has translations for French and Japanese.

I would like to be able to specify the preferred-language for the app (English) and have it be the first choice because it's in the user's browser languages.

Maybe this would look like `primaryLanguage: 'en-US'` or `resolutionOrder: ['en-US', 'fr-CA']`, where items configured here would be considered first before going through the list of browser languages.

Currently, because the user's first language is French, they will receive my French translation which is not how I'd like them to use it if they also know English.

**Comment by adrai** [comment]
Have you already tried with fallbackLng? https://www.i18next.com/principles/fallback#fallback-language

**Comment by morinted** [comment]
Thanks, I think fallbackLng would be for selecting translations that are
missing in the user's language. I'm looking for a way to prioritize certain
languages when the user's browser lists them.

**Comment by adrai** [comment]
What do you mean by: “when the user's browser lists them”?
This plugin is about language detection. 🤷‍♂️

**Comment by adrai** [comment]
Any way... try to create a PR or write your own language detector 🤷‍♂️

**Comment by jamuhl** [comment]
there is no such option...but you can create your own detector: https://github.com/i18next/i18next-browser-languageDetector#adding-own-detection-functionality

**Comment by morinted** [comment]
For the list of languages, I was thinking of leveraging
navigator.languages:
https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/languages

I was going to write my own detector but it never hurts to ask + documents
if anyone else goes down the same path.

Thanks guys.

**Comment by adrai** [comment]
fyi: that’s the same we use here: https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/browserLookups/navigator.js

**Comment by morinted** [comment]
Thank you for that reference, looks like I could sort the found array to have the app's preferred language first in the list.
