### ISSUE TITLE
Can I detect the language when I change the pathname (detect via path)?

### ISSUE THREAD

**Issue by nguyenvantruong17** [i18next/i18next-browser-languageDetector#225]
## 🚀 Feature Proposal

I've detected the language by the **path** order. But when I changed the path, the language does not change. I don't want to use the **changeLanguage** API. I want to sync the language with the browser when I change the URL.

This is my config
```tsx
 detection: {
      order: ['path'],
      lookupFromPathIndex: 0,
      checkWhitelist: true,
 }
```

## Example
Step by step
1. Start with http://domain_name/url (this is default lng)
2. Change the URL to another URL (http://domain_name/en/another-url)

**Comment by jamuhl** [comment]
Works already...if working correctly at all -> if i18next.init runs it sets the language based on detection - if there is no other detection beside path and you do not set cache to eg. cookie or localStorage it will pick up language from path as usual...

you might have to set: `caches: [],` in your detection options to not cache the first detection

**Comment by nguyenvantruong17** [comment]
@jamuhl It still not working. It just detects in the first-time when setup initial i18next.
But, I think you've confused. I mean, change the URL inside App (Using react-router-dom to redirect to another URL. Not reload).

**Comment by jamuhl** [comment]
@nguyenvantruong17 I think you're confused 😉...the detector does not know anything about react-router...and runs only on init...so you will need to call changeLanguage beside navigating to new language on clientside

**Comment by nguyenvantruong17** [comment]
@jamuhl Thanks for your help. I'll close this issue.
