### ISSUE TITLE
Updating Terminology

### ISSUE THREAD

**Issue by kevmathew** [i18next/i18next-browser-languageDetector#226]
## 🚀 Feature Proposal

Hey there!,

I was wondering it there was plans to update terminology in this library.

Per https://github.com/i18next/i18next/issues/1466, i18next v19.5.0 was released and introduced the following changes to terminology:
> - rename option whitelist to supportedLngs
> - rename option nonExpicitWhitelist to nonExplicitSupportedLngs
> - rename function languageUtils.isWhitelisted to languageUtils.isSupportedCode

A similar update to this library to replace `checkForSimilarInWhitelist `

## Motivation

So that consumers who opt-in to more inclusive language, don't have to use outdated configuration names.

## Example

Implemented with backwards compatibility, just like it was done in `i18next`

https://github.com/i18next/i18next/commit/db9077588ebcc7e49932fa36d59d3b70c2a76d2a

Thanks for your time!

**Comment by jamuhl** [comment]
not 100% sure but that was replaced by https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/index.js#L71

or where did you find that term?

**Comment by kevmathew** [comment]
yikes! I'm clearly using an out of date version! Sorry for the confusion @jamuhl!
