### ISSUE TITLE
i18nextLng Local Storage Key/Value Created Even Though Not Used In Configuration

### ISSUE THREAD

**Issue by rabidkitten** [i18next/i18next-browser-languageDetector#229]
## 🐛 Bug Report

The library seemingly is creating a local storage key/value pair called i18nextLng. 

## To Reproduce

All of the configuration (what is pasted below) refers to the language key as "lng" and not i18nextLng. It should be using "lng" everywhere. 

```js
    // order and from where user language should be detected
    order: ['querystring', 'cookie', 'localStorage', 'sessionStorage', 'navigator', 'htmlTag', 'path', 'subdomain'],

    // keys or params to lookup language from
    lookupQuerystring: 'lng',
    lookupCookie: 'lng',
    lookupLocalStorage: 'lng',
    lookupSessionStorage: 'lng',
    lookupFromPathIndex: 0,
    lookupFromSubdomainIndex: 0,

    // cache user language on
    caches: ['localStorage', 'cookie'],
    excludeCacheFor: ['cimode'], // languages to not persist (cookie, localStorage)
    // optional set cookie options, reference:[MDN Set-Cookie docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie)
    cookieOptions: { path: '/', sameSite: 'strict' }
```

## Expected behavior

A key with this name should not be created since it is not configured to use this key name. Because of extensive privacy legislation, it is important that applications know what is being created and what it is being used for. 

## Your Environment

- *runtime version*: node v8.11.3
- *i18next version*: 19.8.4
- *os*: Mac

**Comment by adrai** [comment]
How does your code look like?
Can you create a reproducable example?

**Comment by aellwein** [comment]
I have a same issue here. To reproduce, it's enough to pass basic options to ``init()``, for instance:
```js
i18n
    .use(LanguageDetector)
    .init({
        resources: {
            en: { translation: translationEN },
            de: { translation: translationDE },
        },
        fallbackLng: 'en',
        detection: {
            order: ['navigator']
        }
    });
```
Here i don't want to use localStorage or cookies *intentionally*, but the ``i18nextLng`` entry is created.

P.S.: i found out, that by specifying empty ``caches`` parameter, the localStorage is not used:

```js
i18n
    .use(LanguageDetector)
    .init({
        resources: {
            en: { translation: translationEN },
            de: { translation: translationDE },
        },
        fallbackLng: 'en',
        detection: {
            order: ['navigator'],
            caches: []
        }
    });
```

**Comment by adrai** [comment]
exactly, because caches: ['localStorage', 'cookie'] is default

**Comment by rabidkitten** [comment]
The problem isn't just where it is stored, but also the name of the cookie. I mean, the name is clearly indicated in the config, but it is not calling it "lng" and instead it is calling it "i18nextLng". So it seemingly isn't respecting the naming in the config.

**Comment by adrai** [comment]
@rabidkitten how does your initialization look like?

**Comment by rabidkitten** [comment]
Here is the full file:

import i18n from 'i18next';
import Backend from 'i18next-xhr-backend';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

i18n
  .use(LanguageDetector)
  .use(Backend)
  .use(initReactI18next)
  .init({
    backend: {
      /* translation file path */
      loadPath: '/translations/{{lng}}.json',
    },
    fallbackLng: 'en',
    debug: false,
    /* can have multiple namespace, in case you want to divide a huge
    translation into smaller pieces and load them on demand */
    ns: ['translations'],
    defaultNS: 'translations',
    keySeparator: false,
    interpolation: {
      escapeValue: false,
      formatSeparator: ',',
    },
    react: {
      wait: true,
    },
    // order and from where user language should be detected
    order: ['querystring', 'cookie', 'localStorage', 'sessionStorage', 'navigator', 'htmlTag', 'path', 'subdomain'],

    // keys or params to lookup language from
    lookupQuerystring: 'lng',
    lookupCookie: 'lng',
    lookupLocalStorage: 'lng',
    lookupSessionStorage: 'lng',
    lookupFromPathIndex: 0,
    lookupFromSubdomainIndex: 0,

    // cache user language on
    caches: ['localStorage', 'cookie'],
    excludeCacheFor: ['cimode'], // languages to not persist (cookie, localStorage)
    // optional set cookie options, reference:[MDN Set-Cookie
    // docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie)
    cookieOptions: { path: '/', sameSite: 'strict' },
  });

export default i18n;

**Comment by adrai** [comment]
@rabidkitten your config is wrong...
all detection options needs to be placed inside the detection options:

![image](https://user-images.githubusercontent.com/1086194/103140099-dbda4480-46e2-11eb-93fd-d7bb0d07b103.png)

**Comment by Pierrekfoury** [comment]
I asked myself the same question, but where does 'i18nextLng' come from?
it would be good to clarify that the module adds by default in the localStorage `i18nextLng`
