### ISSUE TITLE
Possibility to prevent saving the value in local storage (only read, no write or change)

### ISSUE THREAD

**Issue by MLui68** [i18next/i18next-browser-languageDetector#233]
## 🚀 Feature Proposal

A callback method to control (or prevent) saving to localstorage. An optional one parameter in .init() to suppress saving. The developer writes the value via the application logic (read only, not add/change is done in the LanguageDetector). Default can be write/read as now.

## Motivation

We are developing an application for Europe, here there are legal requirements that allow saving information to the localstorage only after the user has agreed to this.
Currently, however, the init() already stores the value in the localstorage before the customer agrees.

So a function to suppress saving until the user wants it would be good. 
Ideal would be a callback method that can be appended as an option that can prevent or allow this via a boolean return value.

**Comment by adrai** [comment]
Just set the cache option to an empty array:

instead of caches: ['localStorage', 'cookie']

-> caches: []
