### ISSUE TITLE
'languageOnly' should also be an option for setting the language upon detection

### ISSUE THREAD

**Issue by bpriddy** [i18next/i18next-browser-languageDetector#237]
## 🚀 Feature Proposal

`load: 'languageOnly'` and `nonExplicitSupportedLngs: true` provide good functionality for detecting generalized languages in projects where regional language specificity doesn't provide benefit.  Unintuitively, though, when these options are used, the language is still set to the specific language code.  Language should be set to the base language code as either an implicit decision of one of these 2 config options, or a separate config option should be available, such as `setLanguageOnly: true`

## Motivation

`load: 'languageOnly'` and `nonExplicitSupportedLngs: true` feels incomplete without this.  I am writing my own code to change the language to the base code after the initial language is set

## Example

My default browser language is 'en-US'.  My project supports 'en' and 'fr'.  I can successfully match 'en-US' to 'en', but i18n.language is still set to 'en-US' which creates undesirable results for multiple other aspects of my application, such as i18n subpath routing.

**Comment by adrai** [comment]
https://www.i18next.com/overview/api#language
![image](https://user-images.githubusercontent.com/1086194/115436638-808d0e80-a20b-11eb-96bb-b41b40caaf24.png)

**Comment by bpriddy** [comment]
thanks!
