### ISSUE TITLE
No cookieOptions in the index.d.ts file

### ISSUE THREAD

**Issue by oxilor** [i18next/i18next-browser-languageDetector#238]
The library support the cookieOptions parameter (thanks for that!) that does not have types in the [index.d.ts](https://github.com/i18next/i18next-browser-languageDetector/blob/master/index.d.ts) file.

**Comment by adrai** [comment]
Would you like to create a PR?

**Comment by oxilor** [comment]
I just created a [PR](https://github.com/i18next/i18next-browser-languageDetector/pull/239).

**Comment by adrai** [comment]
Thank you, released with v6.1.1
