### ISSUE TITLE
Minified jQuery File Missing

### ISSUE THREAD

**Issue by RyFive85** [i18next/i18next-browser-languageDetector#241]
The 6.1.1 update seems to have broken everything.  The browser calls out for the minified jQuery file at https://cdnjs.cloudflare.com/ajax/libs/i18next-browser-languagedetector/6.1.1/i18nextBrowserLanguageDetector.min.js, which throws a 404 error for the 6.1.1 version.

**Comment by adrai** [comment]
v6.1.1 was only a typescript addition... there was no build at all...
btw: we do not control cdnjs
