### ISSUE TITLE
🐛 Doesn't respect fallbackLng

### ISSUE THREAD

**Issue by MarkLyck** [i18next/i18next-browser-languageDetector#244]
## 🐛 Bug Report

when using LanguageDetector it does not fall back to the fallbackLng

## To Reproduce

- add resources to i18n.init
- add `LanguageDetector`
- add i18n fallbackLng
- Navigate to webpage using a language that is not in resources and is not the fallback language.

## Expected behavior

When a user enters your website with a language that's not in `i18n` resources, I would expect it to fall back to the `fallbackLng` provided to the init function.

In my case my init looks like this:

```
i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources: {
      en: englishMessages,
      fr: frenchMessages,
    },
    fallbackLng: 'en',
    debug: true,
    interpolation: {
      escapeValue: false,
    },
  })
```

my "browser language" is `en-US`.

When I enter the website, it sets the language to `en-US` a language that doesn't exist in my resources.

<img width="832" alt="Screen Shot 2021-06-16 at 12 41 16" src="https://user-images.githubusercontent.com/6841110/122205093-270a2e80-cea0-11eb-87f1-2937dc4dcfb8.png">

This is in turn causing my UI to show a language that doesn't exist:

<img width="121" alt="Screen Shot 2021-06-16 at 12 41 37" src="https://user-images.githubusercontent.com/6841110/122205137-325d5a00-cea0-11eb-8549-951d408c5dbf.png">

What I expect to see:

<img width="400" alt="Screen Shot 2021-06-16 at 12 46 32" src="https://user-images.githubusercontent.com/6841110/122205828-f5459780-cea0-11eb-9da2-02ab1012690b.png">

For the languages I support, I have a flag and a proper translated word. This means it will break for everyone outside of my currently 2 supported languages.

---

Even if I change the structure of my language to `en-CA` and `fr-CA` instead of simply `fr` and `en`, I will still have the same problem with the language being set to e.g. `da-DK` for danish visitors... When it should be set back to the fallback language if I don't have support for `da-DK`.

## Your Environment

- *runtime version*:  node 12
- *i18next version*:20.3.1
- *i18next-browser-languagedetector*: 6.1.1
- *os*: Mac

**Comment by adrai** [comment]
if you have only a limited set of supported languages, you may want to define the `supportedLngs` option: https://www.i18next.com/overview/configuration-options 
![image](https://user-images.githubusercontent.com/1086194/122206368-93d1f880-cea1-11eb-9d42-d5f1a973a530.png)

you may also want to set the load option to: 'languageOnly'
![image](https://user-images.githubusercontent.com/1086194/122206406-9f252400-cea1-11eb-8db4-643505d7a790.png)

btw: read this:
https://www.i18next.com/overview/api#language
![image](https://user-images.githubusercontent.com/1086194/122205975-23c37280-cea1-11eb-8673-63de3cd63418.png)

**Comment by MarkLyck** [comment]
@adrai oh nice, I did not see this before. Thank you!
