### ISSUE TITLE
Missing TypeScript type for getBestMatchFromCodes

### ISSUE THREAD

**Issue by hug0b** [i18next/i18next-browser-languageDetector#247]
## 🐛 Bug Report

 "getBestMatchFromCodes" detector option is not allowed in TypeScript.

## To Reproduce
[https://codesandbox.io/s/missing-typescript-type-for-getbestmatchfromcodes-nrg5o](
https://codesandbox.io/s/missing-typescript-type-for-getbestmatchfromcodes-nrg5o)

## Expected behavior

 "getBestMatchFromCodes" is a valid option from what I understand.

**Comment by adrai** [comment]
It's not an option at all... it's an internal function of i18next
