### ISSUE TITLE
There should be a output language shorts string list in documentation

### ISSUE THREAD

**Issue by bugatti12345** [i18next/i18next-browser-languageDetector#248]
## Documentation issue

I'm trying to add language-detector in my react i18n, but I have to test what the output short name is since there is no documentation for the complete list of output.

For example, I support `Chinese`, `Korean`, `English`, but Chinese can be `zh-CN`, `zh-hans`, `zh-tw`, Korean can be `ko`, `kr` and Enligsh can be `en-US`, `en-INT`, etc. According to that, I'm not sure to take which string to set in i18n configuration.

In order to make sure I didn't set the wrong string as object key, I need to actually make a language environment in browser and test the actual output. (Surprisingly, I got `zh-CN` for Chinese but only found `zh` in i18n source code in *line 1200 of `i18next.js`*)

As a result, I need to set as follow and no guarantee:

```
resources: {
            kr: {
                translation: kr
            },
            ko: {
                translation: kr
            },
            zh: {
                translation: zh
            },
            'zh-CN': {
                translation: zh
            },
            en: {
                translation: en
            },
            'en-US': {
                translation: en
            },
        },
```

## Motivation

Document the whole language output string list would be a great help!

**Comment by jamuhl** [comment]
Guess you should try to understand what things are...

en --> english
en --> english spoken in US ("Regional")

In detail: https://www.i18next.com/principles/translation-resolution#languages

**Comment by jamuhl** [comment]
further with the options "supportedLngs" and "load" you can set what you like to support in your applikation
