### ISSUE TITLE
Does not reckonize da_DK as da

### ISSUE THREAD

**Issue by simplenotezy** [i18next/i18next-browser-languageDetector#252]
## 🐛 Bug Report / Missing feature

Given an app with two languages: `da` and `en`, if I visit the site with locale: `da-DK` it does not set language to `da`. Only if the language header is `da`, then it works.

## Expected behavior

It should match `da-DK` with `da`, if there is no direct `da-DK` language already

**Comment by adrai** [comment]
Can you please create a reproducible example? With steps to reproduce?

Can't imagine this is not working.
The only thing that could maybe influence is the wrong language code... normally it's da-DK

https://www.i18next.com/how-to/faq#how-should-the-language-codes-be-formatted

**Comment by simplenotezy** [comment]
Well, it does work, it sets the language to "da-DK" but it uses my fallback language which is "en", because we do not have a registered language called "da-DK", we only have a language called "da".

**Comment by simplenotezy** [comment]
As I was trying to create a reproducible example it worked! Not sure what went wrong.

Anyhow, case closed.

Thanks for prompt reply
