### ISSUE TITLE
FR and SP Not Working

### ISSUE THREAD

**Issue by jrock2004** [i18next/i18next-browser-languageDetector#259]
## 🐛 Bug Report

So I am trying to understand why my fr and sp languages are not being used and the fallback is being used. de works just fine for me so not sure what I did wrong with other languages

## To Reproduce

A [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
import i18n from 'i18next';
import LanguageDetector from 'i18next-browser-languagedetector';
import { initReactI18next } from 'react-i18next';

import en from './translations/en.json';
import de from './translations/de.json';
import fr from './translations/fr.json';
import sp from './translations/sp.json';

const resources = {
  de: {
    translation: de,
  },
  en: {
    translation: en,
  },
  fr: {
    translations: fr,
  },
  sp: {
    translations: sp,
  },
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'en',
    interpolation: {
      escapeValue: false,
    },
  });

export default i18n;
```

## Expected behavior

I expect that when I load up `http://localhost:9000?lng=fr` that it will be in french

## Your Environment

- *runtime version*: chrome
- *i18next version*: 21.6.14
- *os*: Mac

**Comment by jrock2004** [comment]
@jamuhl When I run my FR json file thru validator it passes. Could it be something with a value?

**Comment by jamuhl** [comment]
Not really...try setting `debug: true` on i18next init...eventual it gives you some warnings in the browser console.

**Comment by jrock2004** [comment]
![image](https://user-images.githubusercontent.com/655716/164474342-e6c206fa-a0f1-46c4-aeee-d083e0d41fea.png)

**Comment by jamuhl** [comment]
```js
const resources = {
  de: {
    translation: de,
  },
  en: {
    translation: en,
  },
  fr: {
    translations: fr,
  },
  sp: {
    translations: sp,
  },
};
```

see namespace naming -> fr, sp ---> translations instead of translation

**Comment by jrock2004** [comment]
Ughhhh, thanks @jamuhl
