### ISSUE TITLE
Should we check i18next languageOnly option?

### ISSUE THREAD

**Issue by balciseri** [i18next/i18next-browser-languageDetector#26]
`{
      key: 'detect',
      value: function detect(detectionOrder) {
        var _this = this;

        if (!detectionOrder) detectionOrder = this.options.order;

        var detected = [];
        detectionOrder.forEach(function (detectorName) {
          if (_this.detectors[detectorName]) {
            var lookup = _this.detectors[detectorName].lookup(_this.options);
            if (lookup && typeof lookup === 'string') lookup = [lookup];
            if (lookup) detected = detected.concat(lookup);
          }
        });

        var found = void 0;
        detected.forEach(function (lng) {
          if (found) return;
          var cleanedLng = _this.services.languageUtils.formatLanguageCode(lng);
         if (_this.i18nOptions.load === 'languageOnly') cleanedLng = _this.services.languageUtils.getLanguagePartFromCode(cleanedLng);
          if (_this.services.languageUtils.isWhitelisted(cleanedLng)) found = cleanedLng;
        });

        return found || this.i18nOptions.fallbackLng[0];
      }
    }`

What do you think about the bold part? Should we add it?
**if (_this.i18nOptions.load === 'languageOnly') cleanedLng = _this.services.languageUtils.getLanguagePartFromCode(cleanedLng);**

**Comment by jamuhl** [comment]
is it needed? the detection can result in `en-US` where i18next will use `en` if set load to `languageOnly`

**Comment by balciseri** [comment]
I'm not getting what i'm expecting without this fix.
Example:

`var options = {
        debug: true,
        fallbackLng: "en",
        load: 'languageOnly',
        backend: {
            loadPath: './locales/{{lng}}/{{ns}}.json',
            addPath: './locales/add/{{lng}}/{{ns}}',
            allowMultiLoading: false,
            crossDomain: false,
        },
        detection: {
            order: ['localStorage', 'cookie', 'navigator'],
            lookupLocalStorage: 'i18nextLng',
            lookupCookie: 'i18next',
            caches: ['localStorage', 'cookie'],
            cookieMinutes: 60 * 60 * 24 * 365,
        }
    };`

I get : `i18next: languageChanged it-IT` instead of `i18next: languageChanged it`
http://puu.sh/o70T6/1986bec560.png

**Comment by jamuhl** [comment]
yes...language is changed to it-IT does not mean it will load and use it-IT. Internal 18next will always generate an array of language(+region) to lookup: https://github.com/i18next/i18next/blob/master/src/LanguageUtils.js#L58

en-US (without load option) ==> ['en-US', 'en', 'fallbackLng']
en-US (with load option language only) ==> ['en', 'fallbackLng']

i18next.languages should return what you expect. (https://github.com/i18next/i18next/blob/master/src/i18next.js#L193)

**Comment by balciseri** [comment]
To be clear: with **load: 'languageOnly' ** should i get "it-IT" or "it" when performing i18next.language ?
http://puu.sh/o71uy/13a0796b7e.png
Right now i'm getting "it-IT".

**Comment by balciseri** [comment]
Edit: i didn't see the "s" in your answer.
i18next.languages is indeed what i am looking for.
Thanks again.

**Comment by jamuhl** [comment]
closing...if you got any other issue/question feel free to ask.
