### ISSUE TITLE
typo case miss(mix)matching in modue name

### ISSUE THREAD

**Issue by punkratz312** [i18next/i18next-browser-languageDetector#271]
i18next-browser-languagedetector
i18next-browser-language-detector

<img width="385" alt="image" src="https://user-images.githubusercontent.com/8830888/232315962-795c80cb-56d4-4907-b9b9-51bc970b21c6.png">

snake-case is desired case and most common in all projects almost.

<img width="709" alt="image" src="https://user-images.githubusercontent.com/8830888/232315747-d5cdd853-8a78-48a4-8bfc-90e6ae6b436c.png">

<img width="787" alt="image" src="https://user-images.githubusercontent.com/8830888/232315825-1a2357d1-2d3b-4fe6-9aac-bc4b5a5ee598.png">

its kind of easy to migrate: simply deprecate this repo and switch to a new c&p version with a new name.

**Comment by adrai** [comment]
Why is this a problem after so many years?

**Comment by jamuhl** [comment]
it's anyway `i18next`-`specific implementation`-`pluginType` nothing todo with casing

**Comment by punkratz312** [comment]
<img width="691" alt="image" src="https://user-images.githubusercontent.com/8830888/232445717-f7a45e9a-81f8-4399-bdc6-3e01e99eabd5.png">

its called 
    "i18next-http-backend": "2.0.2",
and not 
    "i18next-httpbackend": "2.0.2",
or
    "i18next-httpBackend": "2.0.2",

don´t be lazy around here whats up.

i18next-browser-languageDetector is dangling fix it to
i18next-browser-language-detector 

to much better to read and understand and these are 2 seperate words as you intend in cour camelCasing 🐪  

so please fix it up and use what the whole internet preffesed snake-case

**Comment by jamuhl** [comment]
`i18next-http-backend` 

-> i18next
-> http (using http, request, fetch, ...)
-> backend is the plugin type

**Comment by jamuhl** [comment]
same also for:

i18next-{type}-postProcessor
