### ISSUE TITLE
How to change the localStorage name from i18nextLng to any other name

### ISSUE THREAD

**Issue by ThayaNanthini** [i18next/i18next-browser-languageDetector#276]

**Comment by adrai** [comment]
read the docs: https://github.com/i18next/i18next-browser-languageDetector#detector-options
<img width="351" alt="image" src="https://github.com/i18next/i18next-browser-languageDetector/assets/1086194/6df2f677-7818-4348-a55d-924ba855e1d1">


```js
i18next.use(LanguageDetector).init({
  detection: {
    lookupLocalStorage: 'myChangedName'
  }
});
```
