### ISSUE TITLE
Failed to read the 'cookie' property from 'Document': Cookies are disabled inside 'data:' URLs.

### ISSUE THREAD

**Issue by m-nathani** [i18next/i18next-browser-languageDetector#279]
## To Reproduce

A [minimal reproducible example](https://umai.sentry.io/share/issue/3d60c63ef13b486682d0b9359e136d71/).

We found a report on sentry about failing to read cookies cookies on specific env mentioned below.

```js
import i18n from 'i18next';
import LanguageDetector from 'i18next-browser-languagedetector';
import HttpApi from 'i18next-http-backend';
import { initReactI18next } from 'react-i18next';
...

export const initI18next = ({ languages, defaultLanguage }) => {
  const detectionOptions = {
    order: ['cookie', 'localStorage', 'navigator'],
    lookupCookie: 'i18next-widget',
    lookupLocalStorage: 'i18nextLng-widget',
    caches: ['localStorage', 'cookie'],
    excludeCacheFor: ['cimode'],
  };

  ...

  i18nInstance = i18n.use(HttpApi).use(LanguageDetector).use(initReactI18next);
  i18nInstance
    .init({
      load: 'currentOnly',
      supportedLngs,
      cleanCode: true,
      interpolation: {
        escapeValue: false,
      },
      detection: detectionOptions,
      ns: ['translation', 'common'],
      react: {
        useSuspense: true,
      },
      backend: {
        // locale files can be found in the `public` directory
        loadPath: `${getFilePath()}/locales/{{lng}}/{{ns}}.json`,
        // We don't want to cache the translation files
        requestOptions: {
          cache: 'no-store',
        },
        // Required when widget is embedded in partner website?
        crossDomain: true,
      },
    })
    .then(() => {
      // TODO: Lazy load moment locale?
      moment.locale(i18nInstance?.language);
    });

  return i18nInstance;
};

```

## Expected behavior

Plugin for browser detection should have checks for reading cookies if they are enabled.

something similar to `navigator.cookieEnabled` :

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/cookieEnabled

## Your Environment
- *runtime version*: i.e. node v20
- *i18next version*: 
```
    "i18next": "^23.6.0",
    "i18next-browser-languagedetector": "^7.1.0",
    "i18next-http-backend": "^2.3.1",
    "react-i18next": "^13.3.1",
```
- browser: [Chrome 120.0.0](https://umai.sentry.io/issues/?alert_rule_id=2783259&alert_type=issue&notification_uuid=60424b4f-5dd8-467d-b7cf-e039cb6c1306&project=5264087&query=browser%3A%22Chrome%20120.0.0%22&referrer=event-tags)
- browser.name: [Chrome](https://umai.sentry.io/issues/?alert_rule_id=2783259&alert_type=issue&notification_uuid=60424b4f-5dd8-467d-b7cf-e039cb6c1306&project=5264087&query=browser.name%3AChrome&referrer=event-tags)
- device: [Mac](https://umai.sentry.io/issues/?alert_rule_id=2783259&alert_type=issue&notification_uuid=60424b4f-5dd8-467d-b7cf-e039cb6c1306&project=5264087&query=device%3AMac&referrer=event-tags)
- device.family: [Mac](https://umai.sentry.io/issues/?alert_rule_id=2783259&alert_type=issue&notification_uuid=60424b4f-5dd8-467d-b7cf-e039cb6c1306&project=5264087&query=device.family%3AMac&referrer=event-tags)
- interface_type: [exception](https://umai.sentry.io/issues/?alert_rule_id=2783259&alert_type=issue&notification_uuid=60424b4f-5dd8-467d-b7cf-e039cb6c1306&project=5264087&query=interface_type%3Aexception&referrer=event-tags)
- level: [error](https://umai.sentry.io/issues/?alert_rule_id=2783259&alert_type=issue&notification_uuid=60424b4f-5dd8-467d-b7cf-e039cb6c1306&project=5264087&query=level%3Aerror&referrer=event-tags)
- os: [Mac OS X >=10.15.7](https://umai.sentry.io/issues/?alert_rule_id=2783259&alert_type=issue&notification_uuid=60424b4f-5dd8-467d-b7cf-e039cb6c1306&project=5264087&query=os%3A%22Mac%20OS%20X%20%3E%3D10.15.7%22&referrer=event-tags)
os.name: [Mac OS X](https://umai.sentry.io/issues/?alert_rule_id=2783259&alert_type=issue&notification_uuid=60424b4f-5dd8-467d-b7cf-e039cb6c1306&project=5264087&query=os.name%3A%22Mac%20OS%20X%22&referrer=event-tags)

**Comment by adrai** [comment]
You can do this yourself:

```js
const detectionOptions = {
    order: navigator.cookieEnabled ? ['cookie', 'localStorage', 'navigator'] : ['localStorage', 'navigator'],
    lookupCookie: 'i18next-widget',
    lookupLocalStorage: 'i18nextLng-widget',
    caches: navigator.cookieEnabled ? ['localStorage', 'cookie'] : ['localStorage'],
    excludeCacheFor: ['cimode'],
  };
```

**Comment by adrai** [comment]
fyi: similar discussion: https://github.com/js-cookie/js-cookie/issues/823#issuecomment-1543972888

**Comment by m-nathani** [comment]
> fyi: similar discussion: [js-cookie/js-cookie#823 (comment)](https://github.com/js-cookie/js-cookie/issues/823#issuecomment-1543972888)

Way to go, for creating a robust api ! 😆
