### ISSUE TITLE
addDetector type does not match implementation

### ISSUE THREAD

**Issue by ab-pm** [i18next/i18next-browser-languageDetector#282]
I tried to use chaining on `addDetector` but it didn't work.

The method is declared as 
https://github.com/i18next/i18next-browser-languageDetector/blob/9ad3019513beed29cbd6f070e8f6581564767e96/index.d.ts#L77-L80 but implemented as 
https://github.com/i18next/i18next-browser-languageDetector/blob/9ad3019513beed29cbd6f070e8f6581564767e96/src/index.js#L59-L61

Either it should be declared to return `void` or implemented to `return this;`.

**Comment by adrai** [comment]
addressed with v7.2.1
