### ISSUE TITLE
Webpack warning

### ISSUE THREAD

**Issue by globexdesigns** [i18next/i18next-browser-languageDetector#6]
Similar to this issue: https://github.com/i18next/i18next/issues/477

When `i18next-browser-languageDetector` is loaded via Webpack, the following warning appears:

```
./~/i18next-browser-languagedetector/bin/index.js
Critical dependencies:
1:432-439 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/i18next-browser-languagedetector/bin/index.js 1:432-439
```

Would it be possible to apply the same fix as in i18next issue 477?

**Comment by jamuhl** [comment]
will apply this change on every i18next v2 related repo. just needs a timeframe...hope getting to it on weekend.

**Comment by jamuhl** [comment]
v0.2.0 should have main lead to commonjs, js:next to es
