### ISSUE TITLE
language not detected in 0.2.0

### ISSUE THREAD

**Issue by MartijnR** [i18next/i18next-browser-languageDetector#7]
Just putting this here already but will try to find out more.

In version 0.2.0 the browser language is not detected (`i18next.language` is `undefined`) under certain conditions (in Enketo I only seem to be able to reproduce it in offline-capable pages, were all resources are loaded from the applicationCache - seems weird). The issue occurs after i18next was initialized.

Version 0.1.0 did not have that problem. It might also be a compatibility issue with i18next v 2.2.x as I haven't updated that one yet (due to an issue).

**Comment by MartijnR** [comment]
sorry, it must be something else, not in this module. Will report where applicable when necessary.

**Comment by jamuhl** [comment]
try 0.2.1 should solve this...

**Comment by MartijnR** [comment]
Yes, it does (together with latest XHR and i18next). :+1:

**Comment by adyz** [comment]
I get the same, but looks like this works like a promise.

ex: 

```
i18next.ini(options)
console.log(i18next.language) //undefined
```

the above code outputs `undefined`, but If I add a timeout it logs the proper language
```
setTimeout(function(){
    console.log('I18N', translate.language); // 'en'
}, 2000);
```

How can I know when the language is initialised and available?


Thanks

**Comment by jamuhl** [comment]
the init function is async by nature...=> i18next.init(options, function() { /* ready */ });
