### ISSUE TITLE
Language Detector fails on iOS Device

### ISSUE THREAD

**Issue by narendrastark** [i18next/i18next-browser-languageDetector#78]
I've setted up i18next along with the language detector plugin on my website.
```
i18nextOptions = {
                          load:['en', 'de'],
                          whitelist:['en', 'de'],
                          fallbackLng: 'en',
                          backend: {loadPath: './locales/{{lng}}.json', addPath: './locales/add/{{lng}}.json'},
                          detection: {order: ['querystring', 'cookie', 'navigator', 'localStorage'],
                                      lookupQuerystring: 'lng',
                                      lookupCookie: 'i18next',
                                      lookupLocalStorage: 'i18nextLng',
                                      caches: ['localStorage', 'cookie'],
                                      cookieMinutes: 5},
                          debug: false
                         };
i18next
      .use(window.i18nextXHRBackend)
      .use(window.i18nextBrowserLanguageDetector)
      .init(i18nextOptions, function (err, t) {
```
Evertything is working fine except for iOS Devices. If you open my website on an iOS Device with German language, the website always appears in English. Does anyone know why? Will be greatful for any help.

THX

**Comment by jamuhl** [comment]
does your IOS device submit `de-DE` as language?

you might need to set `load` options to `languageOnly`

**Comment by narendrastark** [comment]
Tried that but it didn't help. Seems like it's only working in Chrome. In Safari, Internet Explorer and Edge the dectection fails (Mobile and Desktop).

**Comment by jamuhl** [comment]
just checked desktop versions safari, ie11, edge...all have navigator.language: https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/browserLookups/navigator.js#L16

**Comment by narendrastark** [comment]
Okay, checked that myself and you're right! I just added 'de-DE'  to the whitelist next to 'de' and 'en' and now it is working.

**Comment by jamuhl** [comment]
related to: https://github.com/i18next/i18next/issues/738
